export const thresholdFieldCatalog = {
    "Process Parameter": [
        "Param ID",
        "Count Name",
        "Consignee Name",
        "Creation Date",
        "Machine No.",
        "Bottom Roll Setting",
        "Top Roll Setting",
        "Break Draft",
        "Total Draft",
        "TPI/TM",
        "Spacer",
        "Traveller",
        "Speed",
        "Make",
        "Denier",
        "Mergen Number",
        "Lycra Draft",
        "Lycra %",
    ],
    "Cotton HVI Data Entry": [
        "Variety",
        "Invoice No",
        "Invoice Date",
        "SCI",
        "Span Length (2.5%)",
        "Mic",
        "GTEX",
        "Maturity",
        "UR",
        "SFI",
        "Elongation",
        "Yellow + B",
        "TrCnt",
        "TrAr",
        "TrID",
        "Invisible Loss %",
        "Trash Content %",
        "RD",
        "Colour Grade",
    ],
    "Fibre Data Entry": [
        "Variety",
        "Invoice No",
        "Invoice Date",
        "Cut Length",
        "Length CV",
        "Mean Denier",
        "CV per Denier",
        "Tenacity",
        "CV per Tenacity",
        "Elongation",
        "CV per Elongation",
        "Crimp (ARC/CM)",
        "Whiteness Index",
        "Spin Finish",
    ],
    "AFIS Data Entry": [
        "Variety",
        "Invoice No",
        "Invoice Date",
        "UQL",
        "L5%",
        "SFC(N)",
        "IFC %",
        "Fibre Neps Gms",
        "SFC(W)",
        "Maturity",
        "Fineness",
        "SCN (gms)",
    ],
    "Moisture Data Entry": [
        "Party Lot No",
        "Variety",
        "Party Name",
        "PR No",
        "Value 1",
        "Value 2",
        "Value 3",
        "Value 4",
        "Value 5",
        "Value 6",
        "Value 7",
        "Value 8",
        "Value 9",
        "Value 10",
        "Average",
    ],
    "Openness Data Entry": [
        "Mixing",
        "Neps +200",
        "Neps +280",
        "Neps +500",
        "Seed Coat Nep",
        "Trash",
        "Visible Foreign Matter",
        "Invisible Foreign Matter",
    ],
    "Between & Within Card Data Entry": [
        "MC Name",
        "Inspection Type",
        "Sample Weight",
        "Hank",
        "Sample Weight Avg",
        "Sample Weight Max",
        "Sample Weight Min",
        "Sample Weight Range",
        "Sample Weight SD",
        "Sample Weight CV",
        "Hank Avg",
        "Hank Max",
        "Hank Min",
        "Hank Range",
        "Hank SD",
        "Hank CV",
    ],
    "Card Thick Place Entry": [
        "ID No.",
        "Date",
        "Time",
        "Machine Reading",
    ],
    "Trials Data Entry Form": [
        "Trial ID",
        "Date",
        "Time",
        "Spinning Machine Name",
        "Autoconer Machine Name",
        "Count Name",
        "Purpose",
        "Trial Name / ID",
        "Type",
        "Nature",
        "Unit No.",
        "Raw Material",
        "Mixing",
        "Yarn Results",
    ],
    "Nati Data Entry": [
        "Nati ID",
        "Entry Date",
        "Variety",
        "MC No",
        "Ratio into size-1.0",
        "Ratio into size-0.7",
        "Ratio into size-0.5",
    ],
    "U% Data Entry": [
        "Date",
        "Shift",
        "Variety",
        "Department",
        "MC No.",
        "U%",
        "CVM",
        "1m CVM",
        "3m CVM",
        "Remarks",
    ],
    "Card DFK Pressure Checking": [
        "DFK",
        "CCD",
        "ICFD (1)",
        "LT",
        "CDS",
        "SILVER DRAFT",
        "ICFD (2)",
        "IDF IN",
        "IDF OUT",
        "AL ON",
    ],
    "COTS Checking": [
        "Checking Type",
        "Inspection Date",
        "Machine No.",
        "Employee Name",
        "LHS Value",
        "RHS Value",
        "LHS Remarks",
        "RHS Remarks",
        "LHS Audio",
        "RHS Audio",
    ],
    "Count Change": [
        "Type",
        "Entry Date",
        "Test No.",
        "RF No.",
        "Lycra Draft",
        "Count Change Type",
        "Count Name From",
        "Count Name To",
        "No. of Readings",
        "Reading No.",
        "Reading Value",
        "Count",
        "CV%",
        "Strength",
        "Mean",
        "CV% 2",
        "CSP",
    ],
    "Ring Frame Log Book": [
        "Inspection Type",
        "Entry Date",
        "Shift",
        "Checker Name",
        "MC No.",
        "Lycra",
        "Bobbin Color",
        "Spindle 1",
        "Spindle 2",
        "Spindle 3",
        "Spindle 4",
        "Spindle 5",
        "Spindle 6",
        "Lycra Missing",
        "Guide Roll Lapping",
        "Others",
        "Total",
        "Out of Center",
        "Fault Cops",
        "Total Cops",
        "Remarks",
        "Comments",
    ],
    "Speed Checking": [
        "Checking Type",
        "Inspection Date",
        "Machine No.",
        "Employee Name",
        "Display Speed",
        "Spindle Speed",
        "Difference",
        "LHS Value",
        "RHS Value",
        "LHS Remarks",
        "RHS Remarks",
        "LHS Audio",
        "RHS Audio",
    ],
    "Lycra Missing": [
        "Checking Type",
        "Inspection Date",
        "Machine No.",
        "Employee Name",
        "LHS Value",
        "RHS Value",
        "LHS Remarks",
        "RHS Remarks",
        "LHS Audio",
        "RHS Audio",
    ],
    "Bottom Apron Checking": [
        "Checking Type",
        "Inspection Date",
        "Machine No.",
        "Employee Name",
        "LHS Value",
        "RHS Value",
        "LHS Remarks",
        "RHS Remarks",
        "LHS Audio",
        "RHS Audio",
    ],
    "Lycra Centering": [
        "Checking Type",
        "Inspection Date",
        "Machine No.",
        "Employee Name",
        "LHS Value",
        "RHS Value",
        "LHS Remarks",
        "RHS Remarks",
        "LHS Audio",
        "RHS Audio",
    ],
    "RSM & Lycrasensor Checking Online": [
        "Checking Type",
        "Inspection Date",
        "Machine No.",
        "Employee Name",
        "LHS Value",
        "RHS Value",
        "LHS Remarks",
        "RHS Remarks",
        "LHS Audio",
        "RHS Audio",
    ],
    "RSM & Lycrasensor Checking Offline": [
        "Checking Type",
        "Inspection Date",
        "Machine No.",
        "Employee Name",
        "LHS Value",
        "RHS Value",
        "LHS Remarks",
        "RHS Remarks",
        "LHS Audio",
        "RHS Audio",
    ],
    "Wheel Change": [
        "Type",
        "Wheel Change Type",
        "Date",
        "Test No.",
        "RF No.",
        "FM No.",
        "FR No.",
        "Count From",
        "Lycra Type",
        "Lycra Draft",
        "Slub Code",
        "Ramp",
        "Offset On/Off",
        "Cop or Cone Condition",
        "Product Qty (Kgs)",
        "Raving Hank",
        "Back Roll Wheel",
        "Change Pinion",
        "BDW",
        "BD",
        "DCA",
        "DCB",
        "DFF",
        "DC",
        "TCW",
        "TW",
        "B",
        "A",
        "D",
        "C",
        "TPI/TM",
        "Winding - E/F",
        "Ratchet Wheel",
        "Travellers No.",
        "Spacer",
        "Cop Weight",
        "Cop Weight (Grms)",
        "Speed Initial (RPM)",
        "Speed Max (RPM)",
        "Empties Colour",
        "Total Draft",
        "Existing",
        "Proposed",
    ],
    WheelChange: [
        "Mixing",
        "Blend %",
        "Doff-Hank",
        "Feed Weight",
        "Speed",
        "Licker-In Speed 1",
        "Cylinder Speed",
        "Flats Speed in m/min",
        "Feed Plate to Licker-In",
        "SFL",
        "SFD",
        "Cylinder to Flats",
        "Cylinder in Doffer",
        "Web Speed Dots MT /AI",
        "LC-Wing Setting",
        "DK-NK Beater Speed",
    ],
    "Ribbon Lap CV Data Entry": [
        "Record Date",
        "Machine Name",
        "Variety",
        "Lap Type",
        "Lap Weight",
        "Sample 1",
        "Sample 2",
        "Sample 3",
        "Sample 4",
        "Sample 5",
        "Sample 6",
        "Sample 7",
        "Sample 8",
        "Average",
        "Max",
        "Min",
        "Range",
        "SD",
        "CV%",
    ],
    "PP - Autoconer Q2": [
        "Count Name",
        "Consignee Name",
        "N",
        "S",
        "L",
        "LH1",
        "LH2",
        "LH3",
        "LH4",
        "LH5",
        "LH6",
        "THT",
        "TH1",
        "TH2",
        "TH3",
        "TH4",
        "TH5",
        "TH6",
        "CP",
        "CM",
        "CCP",
        "CCM",
        "PC",
        "Fault Distance",
        "No. of Faults",
        "JP",
        "JM",
        "UP",
        "FL",
        "FLH1",
        "FLH2",
        "FLH3",
        "FLH4",
        "FD",
        "FDH1",
        "FDH2",
        "FDH3",
        "FDH4",
        "FDH5",
        "Reference Length",
        "Measurement",
        "Upper Alarm Limit",
        "Lower Alarm Limit",
        "Action",
    ],
    "PP - Autoconer Q3": [
        "Count Name",
        "Consignee Name",
        "NSL1",
        "NSL2",
        "NSL3",
        "NSL4",
        "NSL5",
        "NSL6",
        "NSL7",
        "T1",
        "T2",
        "T3",
        "T4",
        "T5",
        "PF Sensing",
        "PF No. of Periods",
        "OC",
        "CP",
        "CM",
        "CCP1",
        "CCP2",
        "CCM1",
        "CCM2",
        "JP1",
        "JP2",
        "JP3",
        "JP4",
        "JP5",
        "JP6",
        "JP7",
        "JP Clearing",
        "JP U%",
        "JP JM",
        "FD1",
        "FD2",
        "FD3",
        "FD4",
        "FD5",
        "FD6",
        "Reference Length",
        "Suction",
        "Measurement",
        "Upper Limit",
        "Lower Limit",
        "Action",
        "Suction Status",
        "Blocking",
    ],
    "Rewinding Study": [
        "Test No.",
        "Date",
        "Count Name (From)",
        "Auto Coner No.",
        "Drum From/To",
        "No. of Cones",
        "Cone Tip",
        "Drum No.",
        "Weight",
        "No. of Cuts",
        "Break / 1 Lakh Meter",
    ],
    "Cone Density": [
        "Test No.",
        "Date",
        "Count Name (From)",
        "Auto Coner No.",
        "Base Dia (E)",
        "Nose Dia (E)",
        "Drum From/To",
        "Cone Tip",
        "Base Dia",
        "Nose Dia",
        "Cone Weight",
        "Cone Trav",
        "Density",
        "Hardness",
    ],
    "Cone Packing Audit": [
        "Type",
        "Test No.",
        "Entry Date",
        "Count Name",
        "Auto Coner No.",
        "Drum No.",
        "Box Colour",
        "Cone Colour",
        "Gum Tape Colour",
        "Count Label",
        "Cone Damage",
        "Cover Missing",
        "Cone Hardness",
        "Stap Cone",
        "Disk",
        "Barcode",
        "Center Pad",
        "Net Weight",
        "Tare Weight",
        "Strap Colour",
    ],
    "Lycra Checking": [
        "Test No.",
        "Entry Date",
        "Lycra Draft",
        "Count Name",
        "No. of Readings",
        "Lycra Weight",
        "Fabric Weight",
        "Total Weight",
        "Lycra %",
        "Reading 1",
        "Reading 2",
        "Reading 3",
        "Reading 4",
        "Reading 5",
    ],
    "Count Wise Cuts Record": [
        "Date",
        "Machine No.",
        "Count",
        "Drums From/To",
        "Crane Tip",
        "Lot No.",
        "Frame No.",
        "Metric 1",
        "Metric 2",
        "Metric 3",
        "Metric 4",
        "Metric 5",
    ],
    "Splice Strength": [
        "Test No.",
        "Date",
        "Count Name",
        "Auto Coner No.",
        "Drum From",
        "Drum To",
        "Cone Tip",
        "CSP Value",
        "Average",
        "Drum No",
        "No. of Readings",
        "Reading 1",
        "Reading 2",
        "Reading 3",
        "Reading 4",
        "Reading 5",
    ],
    "Drum wise Appearance": [
        "Test No.",
        "Entry Date",
        "Count Name",
        "Auto Coner No.",
        "Drum From",
        "Drum To",
        "Remarks",
        "Drum Appearance",
    ],
    "CSP Parameter Entries": [
        "Act Count",
        "Strength",
        "Count CV",
        "Strength CV",
        "CSP",
        "Cone Color",
        "U%",
        "CVM",
        "1Mtr CV",
        "3Mtr CV",
        "10Mtr CV",
        "BR 1.5mm",
        "CVB",
        "Thin -50%",
        "Thick +50%",
        "Neps +200%",
        "Thin -40%",
        "Thick +35%",
        "Thick +70%",
        "Neps +140%",
        "Thin -30%",
        "Neps +400%",
        "Total",
    ],
    "U% Parameter Entries": [
        "Act Count",
        "Strength",
        "CV1",
        "CV2",
        "CSP",
        "Cone Color",
        "U%",
        "CVM",
        "1Mtr CV",
        "3Mtr CV",
        "10Mtr CV",
        "BR 1.5mm",
        "CVB",
        "Thin -50%",
        "Thick +50%",
        "Neps +200%",
        "Thin -40%",
        "Thick +35%",
        "Thick +70%",
        "Neps +140%",
        "Thin -30%",
        "Neps +400%",
        "TOTAL",
    ],
    "Blow Room Sync": [
        "Entry Date",
        "Line No.",
        "Variety",
        "Checked By",
        "Beater",
        "Total Time",
        "Value A",
        "Value B",
        "Value C",
        "Sync Percentage",
    ],
    "BR Waste Study Entry": [
        "Waste Type",
        "Machine",
        "Weight",
        "Percentage",
        "Remarks",
    ],
    "Drop Test Data Entry": [
        "Drop ID",
        "Date",
        "Variety",
        "Blend",
        "No. of Tufts",
        "Tuft Variety",
        "Actual Wt.",
        "Display Wt.",
        "Average Wt.",
        "Diff (Display Wt. - Actual Wt.)",
        "Ratio (Average Wt. / Total) * 100",
    ],
    "SMXCots Change Data Entry": [
        "S. No.",
        "Date",
        "MC Name",
        "Item Status",
        "Item Remarks",
    ],
    "SMX Breaks Study Report": [
        "Simplex No.",
        "Date",
        "Start Time",
        "End Time",
        "Total Time",
        "TPI",
        "TPM",
        "Start HK",
        "Finish HK",
        "Average Speed",
        "Hank",
        "Mixing",
        "Roving HK",
        "Doff Length",
        "RH%",
        "TEMP%",
        "TT_SPDL",
        "Running Spdl",
        "Ideals",
        "S. Name",
    ],
    "1 Yard / Half Yard CV Entry": [
        "S. No.",
        "Date",
        "Machine Number",
        "Remarks",
        "AVG (1 Yard)",
        "HANK (1 Yard)",
        "SD (1 Yard)",
        "CV% (1 Yard)",
        "AVG (1/2 Yard)",
        "HANK (1/2 Yard)",
        "SD (1/2 Yard)",
        "CV% (1/2 Yard)",
    ],
    "Draw Frame Cots Data Entry": [
        "Date",
        "Shift",
        "MC Name",
        "Fan Waste",
        "Cot Change",
        "Stripper W",
        "Thick Place",
        "Auto Level",
        "Silver Mon",
        "Mass Thick",
        "Scanning R",
    ],
    "PP - Breaker Drawing": [
        "Count Name",
        "Consignee Name",
        "Make",
        "No. of Ends",
        "Bottom Roll Setting",
        "Breaker's Draft",
        "Total Draft",
        "Hank",
        "Web Tension Draft",
        "Trumpet Size",
        "Delivery Speed",
        "Pressure Bar",
    ],
    "PP - Finisher Drawing": [
        "Count Name",
        "Consignee Name",
        "Make",
        "No. of Ends",
        "Bottom Roll Setting",
        "Break Draft",
        "Total Draft",
        "Web Tension Draft",
        "Trumpet Size",
        "Insert Size",
        "Web Funnel Size",
        "Delivery hank",
        "Delivery Speed",
        "Pressure Bar",
        "Scanning Rolls Size",
    ],
};

export const getThresholdFieldsForScreen = (screenName) =>
    thresholdFieldCatalog[screenName] || [];
