export const thresholdFieldCatalog = {
    "Mixing::Process Parameter": [
        "Process Parameter ID",
        "Created Date",
        "Count Name",
        "Consignee Name",
        "Lot No.",
        "Blend-1",
        "Cut Length",
        "Tenacity",
        "Elongation",
        "Merge No.",
    ],
    "Mixing::AFIS-6 Cotton": [
        "Lot No.",
        "Variety",
        "Invoice Date",
        "Created Date",
        "Mc. Name",
        "Blow Room",
        "Carding",
        "Breaker Drawing",
        "Finisher Drawing",
        "Comber",
        "SCP NEP Count",
        "L(W)",
        "L(W) CV",
        "SCF(W)<12.70mm",
        "UQL(w)",
        "L(n)",
        "L(n)CV",
        "SCF(n)<12.70mm",
        "5%L(n)",
    ],
    "Mixing::AFIS-6 MMF": [
        "Lot No.",
        "Variety",
        "Invoice Date",
        "Created Date",
        "Mc. Name",
        "Blow Room",
        "Carding",
        "Breaker Drawing",
        "Finisher Drawing",
        "Comber",
        "Total Nep Count / g",
        "Total Nep mean size",
        "Fiber Nep Count",
        "Fiber Nep Mean Size",
        "SC Nep Count",
        "SC Nep Mean Size",
        "L(w)",
        "L(w)CV",
        "SCF(w)<12.70mm",
        "UQL(w)",
        "L(n)",
        "L(n)CV",
        "SCF(n)<12.70mm",
        "5%L(n)",
        "Fitness Index",
        "Maturity Ratio Mat 1",
        "IFC%",
        "50%L(n)",
        "Cut Length(n)",
        "Fineness Den",
        "Fineness CV",
        "Long Fiber >45.60mm",
        "Long Fiber Count >45.60mm",
    ],
    "Blow Room::Process Parameter": [
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
        "Line Numbers",
        "Rotary Beater Speed",
        "Depth",
        "MPM Delivery Speed",
        "MPM Delivery Pascals",
        "Condensor Speed",
        "RK Feed Roll Beater",
        "RK Beater Speed",
        "Flexi to Feed Roll Beater",
        "Flexi Beater Speed",
        "Scutcher No",
        "RK MO Speed",
        "KB Speed",
        "Grid Bar",
        "Lap Weight",
        "Uniclean",
        "SRS",
        "RK Flexi",
    ],
    "Carding::Process Parameter": [
        "Entry ID",
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
        "Machine No.",
        "Lickerin Speed",
        "Cylinder Speed",
        "Flats Speed",
        "Delivery Speed",
        "Draft",
        "Tension Draft",
        "Delivery Hank",
        "Feed Roll to Lickerin",
        "Lickerin to Cylinder",
        "Cylinder to Flats",
        "Cylinder to Doffer",
        "SFL",
        "SFD",
        "Lickerin",
        "Cylinder",
        "Doffer",
        "Flats",
    ],
    "Simplex::Process Parameter": [
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
        "Machine No.",
        "Make",
        "Delivery Hank",
        "TPI / TM",
        "Speed",
        "Bottom Roller Setting",
        "Top Roller Setting",
        "Break Draft",
        "Total Draft",
        "Creel Draft",
        "Falls twister Grooves",
        "Spacer",
        "Top Arm Pressure",
        "Back Condensor",
        "Middle Condensor",
        "Front Condensor",
        "Coils/Inch",
        "Lifter Combination Wheel",
        "Lifter Wheel",
        "Tension Wheel",
    ],
    "Spinning::Process Parameter": [
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
        "Machine No.",
        "Bottom Roll Setting",
        "Top Roll Setting",
        "Break Draft",
        "Total Draft",
        "TPI/TM",
        "Spacer",
        "Traveller",
        "Speed",
        "Make",
        "Denier",
        "Mergen Number",
        "Slub Partcy Code",
        "Slub / Mtr",
        "Pause Min",
        "Pause Max",
        "Slub Min",
        "Slub Max",
        "Thickness Min",
        "Thickness Max",
        "Ramp",
        "Offset",
        "Lycra Draft",
        "Lycra %",
    ],
    "Autoconer::Process Parameter": [
        "Count Name",
        "Consignee Name",
        "Machine No.",
        "Drum No.",
        "Speed",
        "P Cone Identification",
        "Cone Weight",
        "Initial Winding Tension",
        "Standard Winding Tension",
        "Touch Winding Tension",
        "Release Add Tension",
        "Tension Release End Yarn Layer",
        "Tension Release Decrease Ratio",
        "Tension Release Valid Yarn Layer",
        "Splicing Setting",
        "Water On / Off",
        "Splicing Length Adjust Parameter",
        "Splicing Nozzle",
        "Cradle Pressure",
        "Cone Density",
        "Cone / Cops",
    ],
    "Process Parameter": [
        "Param ID",
        "Count Name",
        "Consignee Name",
        "Creation Date",
        "Machine No.",
        "Bottom Roll Setting",
        "Top Roll Setting",
        "Break Draft",
        "Total Draft",
        "TPI/TM",
        "Spacer",
        "Traveller",
        "Speed",
        "Make",
        "Denier",
        "Mergen Number",
        "Lycra Draft",
        "Lycra %",
    ],
    "Cotton HVI Data Entry": [
        "Variety",
        "Invoice No",
        "Invoice Date",
        "Created Date",
        "SCI",
        "Span Length (2.5%)",
        "Mic",
        "GTEX",
        "Maturity",
        "UR",
        "SFI",
        "Elongation",
        "Yellow + B",
        "TrCnt",
        "TrAr",
        "TrID",
        "Invisible Loss %",
        "Trash Content %",
        "RD",
        "Colour Grade",
    ],
    "Fibre Data Entry": [
        "Variety",
        "Invoice No",
        "Invoice Date",
        "Created Date",
        "Cut Length",
        "Length CV",
        "Mean Denier",
        "CV per Denier",
        "Tenacity",
        "CV per Tenacity",
        "Elongation",
        "CV per Elongation",
        "Crimp(ARC/CM)",
        "Whiteness Index",
        "Spin Finish",
    ],
    "AFIS Data Entry": [
        "Variety",
        "Invoice No",
        "Invoice Date",
        "Created Date",
        "UQL",
        "L5%",
        "SFC(N)",
        "IFC %",
        "Fibre Neps Gms",
        "SFC(W)",
        "Maturity",
        "Fineness",
    ],
    "Moisture Data Entry": [
        "Created Date",
        "Party Lot No",
        "Variety",
        "Party Name",
        "PR No",
        "Value 1",
        "Value 2",
        "Value 3",
        "Value 4",
        "Value 5",
        "Value 6",
        "Value 7",
        "Value 8",
        "Value 9",
        "Value 10",
        "Average",
    ],
    "Openness Data Entry": [
        "Created Date",
        "Actual Specific Volume (Target)",
        "No. of Entries (N)",
        "B/R Line No",
        "Machine Name",
        "Beater Type",
        "Beater Speed (RPM)",
        "Weight (M)",
        "Volume 1",
        "Volume 2",
        "Average Volume (V)",
        "Apparent Specific Vol (A=V/M)",
        "Actual Op. Value (AOV)",
        "Avg. Weight (M)",
        "Avg. Volume (V)",
        "Average of Apparent Specific Vol (A=V/M)",
        "Average of Actual Op. Value (AOV)",
        "Openness %",
        "Overall Openness Efficiency (%)",
    ],
    "Between & Within Card Data Entry": [
        "Entry ID",
        "Test ID",
        "MC Name",
        "Inspection Type",
        "Number of Entries (N)",
        "Sample Weight",
        "Hank",
        "Sample Weight Calculations - Avg",
        "Sample Weight Calculations - Max",
        "Sample Weight Calculations - Min",
        "Sample Weight Calculations - Range",
        "Sample Weight Calculations - SD",
        "Sample Weight Calculations - CV",
        "Hank Calculations - Avg",
        "Hank Calculations - Max",
        "Hank Calculations - Min",
        "Hank Calculations - Range",
        "Hank Calculations - SD",
        "Hank Calculations - CV",
    ],
    "Thick place & CV": [
        "Entry ID",
        "Time",
        "Machine",
        "Card Thick Place Value",
        "5m CV",
    ],
    "Carding NRE%": [
        "Entry ID",
        "Machine Model",
        "Mc Name",
        "Cylinder Wire Specification - Specs",
        "Cylinder Wire Specification - Tonnage in Kgs (1)",
        "Cylinder Wire Specification - Tonnage in Kgs (2)",
        "Doffer Wire Specification - Specs",
        "Doffer Wire Specification - Tonnage in Kgs (1)",
        "Doffer Wire Specification - Tonnage in Kgs (2)",
        "Flat Wire Specification - Specs",
        "Flat Wire Specification - Tonnage in Kgs (1)",
        "Flat Wire Specification - Tonnage in Kgs (2)",
        "Lickerin Wire Specification - Specs",
        "Lickerin Wire Specification - Tonnage in Kgs (1)",
        "Lickerin Wire Specification - Tonnage in Kgs (2)",
        "Silver Hank",
        "Delivery Mtr / Min",
        "Fibre Nep / Gms card mat",
        "Fibre Nep / Gms in Silver",
        "Carding NRE%",
    ],
    "Individual Card performance Data": [
        "Type",
        "Carding Machine No.",
        "Entry ID",
        "Time",
        "Raw Material / Mixing",
        "Count Name",
        "Spinning Machine Name",
        "Autoconer Machine Name",
        "Product",
        "Nature of Trial",
        "Total Cuts",
        "Neps Cuts",
        "Short Cuts",
        "Long Cuts",
        "Thin Cuts",
        "CP",
        "CM",
        "CCP",
        "CCM",
        "JP",
        "A1",
        "A2",
        "A3",
        "A4",
        "B1",
        "B2",
        "B3",
        "B4",
        "C1",
        "C2",
        "C3",
        "C4",
        "D1",
        "D2",
        "D3",
        "D4",
        "E",
        "F",
        "G",
        "H1",
        "H2",
        "I1",
        "I2",
        "CVP",
        "User ID",
        "U%",
        "CVM",
        "CVM cv%",
        "CVM 10 mtr",
        "DR 1.5m",
        "Thin -50%",
        "Thick +50%",
        "Neps +200%",
        "Total (Regular)",
        "Thin -40%",
        "Thick +35%",
        "Neps +140%",
        "Total (HS)",
        "Thin -30%",
        "Count",
        "CSP",
        "Yarn Remarks (optional)",
    ],
    "Carding::Nati Data Entry": [
        "Entry ID",
        "Variety",
        "Number of Neps Entries",
        "MC No",
        "Ratio into size-1.0",
        "Ratio into size-0.7",
        "Ratio into size-0.5",
    ],
    "Nati Data Entry": [
        "Entry ID",
        "Variety",
        "Number of Neps Entries",
        "MC No",
        "Ratio into size-1.0",
        "Ratio into size-0.7",
        "Ratio into size-0.5",
    ],
    "Carding::U% Data Entry": [
        "Entry ID",
        "Shift",
        "Variety",
        "MC No.",
        "U%",
        "CVM",
        "1mCV",
        "3mCV",
        "Remarks",
    ],
    "Comber::U% Data Entry": [
        "Entry ID",
        "Shift",
        "Variety",
        "Department",
        "MC No.",
        "U%",
        "CV in Metres",
        "1m CV in Metres",
        "3m CV in Metres",
        "Remarks",
    ],
    "Comber NRE%": [
        "Entry ID",
        "Silver Hank",
        "Delivery Mtr / Min",
        "Comber Neps / Min",
        "Feed in mm / Nep",
        "Fiber Nep in Comber Lap / Gms",
        "Fiber Nep / Gms in Silver",
        "Comber NRE%",
    ],
    "Comber Efficiency": [
        "Entry ID",
        "Mc Name",
        "50% span length in LAP",
        "50% span length in Sliver",
        "Combing Efficiency",
    ],
    "Comber Nolis %": [
        "Test ID",
        "Machine ID",
        "Total Test",
        "Number of Entries (N)",
        "Tester",
        "Std. Noils %",
        "Noils %",
        "Sample No",
        "Sliver Wt",
        "Noils Wt",
    ],
    "U% Data Entry": [
        "Date",
        "Shift",
        "Variety",
        "MC No.",
        "U%",
        "CVM",
        "1mCV",
        "3mCV",
        "Remarks",
    ],
    "Card DFK Data": [
        "Entry ID",
        "DFK",
        "CCD",
        "ICFD (1)",
        "LT",
        "CDS",
        "SILVER DRAFT",
        "ICFD (2)",
        "IDF IN",
        "IDF OUT",
        "AL ON",
    ],
    "COTS Checking": [
        "Checking Type",
        "Inspection Date",
        "Machine No.",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Count Change": [
        "RF No.",
        "Lycra Draft",
        "Count Change Type",
        "Count Name (From)",
        "Count Name (To)",
        "No. of Readings",
        "Generated Rows",
        "Reading No.",
        "Reading Value",
        "Count",
        "CV%",
        "Strength",
        "Mean",
        "CV% 2",
        "CSP",
        "Reading Avg",
        "Count Avg",
        "Strength Avg",
        "Overall CSP",
    ],
    "Ring Frame Log Book": [
        "Inspection Type",
        "Entry Date",
        "Shift",
        "Checker Name",
        "MC No.",
        "Lycra",
        "Bobbin Color",
        "Spindle 1",
        "Spindle 2",
        "Spindle 3",
        "Spindle 4",
        "Spindle 5",
        "Spindle 6",
        "Lycra Missing",
        "Guide Roll Lapping",
        "Others",
        "Total",
        "Out of Center",
        "Out of Center AC",
        "Out of Center RF",
        "Fault Cops",
        "Fault Cops AC",
        "Fault Cops RF",
        "Total Cops",
        "Total Cops AC",
        "Total Cops RF",
        "Grand Total",
        "Comments",
    ],
    "Speed Checking": [
        "Checking Type",
        "Inspection Date",
        "Machine",
        "Display Speed",
        "Spindle Speed",
        "Difference",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Lycra Missing": [
        "Checking Type",
        "Inspection Date",
        "Machine",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Bottom Apron Checking": [
        "Checking Type",
        "Inspection Date",
        "Machine",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Lycra Out of Centering": [
        "Checking Type",
        "Inspection Date",
        "Machine",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Online": [
        "Checking Type",
        "Inspection Date",
        "Machine",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Offline": [
        "Checking Type",
        "Inspection Date",
        "Machine",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Draw Frame::Wheel Change": [
        "Line Type",
        "Machine No.",
        "Wheel Change Type",
        "Mixing - Existing",
        "Mixing - Proposed",
        "Blend % - Existing",
        "Blend % - Proposed",
        "Del-Hank - Existing",
        "Del-Hank - Proposed",
        "Feed Hank - Existing",
        "Feed Hank - Proposed",
        "No. of Ends - Existing",
        "No. of Ends - Proposed",
        "Speed - Existing",
        "Speed - Proposed",
        "Draft Constant - Existing",
        "Draft Constant - Proposed",
        "NW1 - Existing",
        "NW1 - Proposed",
        "NW2 - Existing",
        "NW2 - Proposed",
        "Total Draft - Existing",
        "Total Draft - Proposed",
        "BDCP (W4 / Break Draft) - Existing",
        "BDCP (W4 / Break Draft) - Proposed",
        "Creel Tension (W1VWW2) / Creel Tension Draft - Existing",
        "Creel Tension (W1VWW2) / Creel Tension Draft - Proposed",
        "Feed Tension (W8/VEG) / Feed Tension Draft - Existing",
        "Feed Tension (W8/VEG) / Feed Tension Draft - Proposed",
        "Web Tension (W3) / Web Tension Draft - Existing",
        "Web Tension (W3) / Web Tension Draft - Proposed",
        "Trumpet - Existing",
        "Trumpet - Proposed",
        "Bottom Roller Setting Front Zone - Existing",
        "Bottom Roller Setting Front Zone - Proposed",
        "Bottom Roller Setting Back Zone - Existing",
        "Bottom Roller Setting Back Zone - Proposed",
        "Total Draft (Formula) - Existing",
        "Total Draft (Formula) - Proposed",
        "Total Draft from G1/G2 Combinations - Existing",
        "Total Draft from G1/G2 Combinations - Proposed",
        "G1/G2 - Existing",
        "G1/G2 - Proposed",
        "BDCP (C4) / Break Draft - Existing",
        "BDCP (C4) / Break Draft - Proposed",
        "Web Tension (C3) / Web Tension Draft - Existing",
        "Web Tension (C3) / Web Tension Draft - Proposed",
        "Total Draft Constant - Existing",
        "Total Draft Constant - Proposed",
        "Break Draft - Existing",
        "Break Draft - Proposed",
        "Back Roller Pulley Dia (W4) - Existing",
        "Back Roller Pulley Dia (W4) - Proposed",
        "Middle Roller Pulley (VV) - Existing",
        "Middle Roller Pulley (VV) - Proposed",
        "Creel Tension (W1) / Creel Draft - Existing",
        "Creel Tension (W1) / Creel Draft - Proposed",
        "Web Tension Wheel (W3) / Web Tension Draft - Existing",
        "Web Tension Wheel (W3) / Web Tension Draft - Proposed",
        "Bottom Roller Setting Front Zone / Gauge in MM - Existing",
        "Bottom Roller Setting Front Zone / Gauge in MM - Proposed",
        "Bottom Roller Setting Back Zone / Gauge in MM - Existing",
        "Bottom Roller Setting Back Zone / Gauge in MM - Proposed",
        "Scanning Roller in mm - Existing",
        "Scanning Roller in mm - Proposed",
        "Scanning Roller Load (kg) - Existing",
        "Scanning Roller Load (kg) - Proposed",
        "Sliver Funnel - Existing",
        "Sliver Funnel - Proposed",
        "Web Guide Tube Dia - Existing",
        "Web Guide Tube Dia - Proposed",
        "Insert Bore Dia - Existing",
        "Insert Bore Dia - Proposed",
        "Break Draft Wheel (W4) / Break Draft (VV) - Existing",
        "Break Draft Wheel (W4) / Break Draft (VV) - Proposed",
        "Break Draft Wheel (W4) / Break Draft - Existing",
        "Break Draft Wheel (W4) / Break Draft - Proposed",
        "Feed Tension Wheel (W8) / Feed Tension Draft - Existing",
        "Feed Tension Wheel (W8) / Feed Tension Draft - Proposed",
        "Break Draft Wheel / Break Draft - Existing",
        "Break Draft Wheel / Break Draft - Proposed",
    ],
    "Wheel Change": [
        "Wheel Change Type",
        "Test No",
        "R/F No.",
        "Count From - Existing",
        "Count From - Proposed",
        "Lycra Type - Existing",
        "Lycra Type - Proposed",
        "Lycra Draft - Existing",
        "Lycra Draft - Proposed",
        "Slub Code - Existing",
        "Slub Code - Proposed",
        "Ramp - Existing",
        "Ramp - Proposed",
        "Offset On/Off - Existing",
        "Offset On/Off - Proposed",
        "Cop or Cone Condition - Existing",
        "Cop or Cone Condition - Proposed",
        "Product Qty (Kgs) - Existing",
        "Product Qty (Kgs) - Proposed",
        "Roving Hank - Existing",
        "Roving Hank - Proposed",
        "Raving Hank - Existing",
        "Raving Hank - Proposed",
        "Back Roll Wheel - Existing",
        "Back Roll Wheel - Proposed",
        "Change Pinion - Existing",
        "Change Pinion - Proposed",
        "BDW - Existing",
        "BDW - Proposed",
        "BD - Existing",
        "BD - Proposed",
        "DCA - Existing",
        "DCA - Proposed",
        "DCB - Existing",
        "DCB - Proposed",
        "DFC - Existing",
        "DFC - Proposed",
        "DFF - Existing",
        "DFF - Proposed",
        "DC - Existing",
        "DC - Proposed",
        "TCW - Existing",
        "TCW - Proposed",
        "TW - Existing",
        "TW - Proposed",
        "B - Existing",
        "B - Proposed",
        "A - Existing",
        "A - Proposed",
        "D - Existing",
        "D - Proposed",
        "C - Existing",
        "C - Proposed",
        "TPI/TM - Existing",
        "TPI/TM - Proposed",
        "TPM - Existing",
        "TPM - Proposed",
        "Winding length in meters - Existing",
        "Winding length in meters - Proposed",
        "Ratchet Wheel - Existing",
        "Ratchet Wheel - Proposed",
        "Travellers No. - Existing",
        "Travellers No. - Proposed",
        "Spacer - Existing",
        "Spacer - Proposed",
        "Cop Weight - Existing",
        "Cop Weight - Proposed",
        "Cop Weight (Grms) - Existing",
        "Cop Weight (Grms) - Proposed",
        "Speed Initial (RPM) - Existing",
        "Speed Initial (RPM) - Proposed",
        "Speed Max (RPM) - Existing",
        "Speed Max (RPM) - Proposed",
        "Empties Colour - Existing",
        "Empties Colour - Proposed",
        "Total Draft - Existing",
        "Total Draft - Proposed",
        "Range - Existing",
        "Range - Proposed",
        "Core Condition - Existing",
        "Core Condition - Proposed",
        "Production (Kgs) - Existing",
        "Production (Kgs) - Proposed",
        "EOW - Existing",
        "EOW - Proposed",
        "EPI - Existing",
        "EPI - Proposed",
        "Speed Front (RPM) - Existing",
        "Speed Front (RPM) - Proposed",
        "Speed (RPM) - Existing",
        "Speed (RPM) - Proposed",
    ],
    WheelChange: [
        "Type",
        "Entry ID",
        "CDG No. (Existing)",
        "CDG No. (Proposed)",
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Weight",
        "Licker-in Speed 1",
        "Licker-in Speed 2",
        "Cylinder Speed",
        "Flats Speed in mm/min",
        "Feed Plate to Licker-in",
        "SFL",
        "SFD",
        "Cylinder to Flats",
        "Cylinder to Doffer",
        "Web Speed Draft MW(V4)",
        "LC-Wing Setting",
        "BR-RK Beater Speed",
        "Remarks (optional)",
    ],
    "Ribbon Lap CV1M Data Entry": [
        "Entry ID",
        "Machine Name",
        "Variety",
        "Lap Weight (KGs)",
        "Lap Length (Mts)",
        "Grams / Meter",
        "Sample 1",
        "Sample 2",
        "Sample 3",
        "Sample 4",
        "Sample 5",
        "Average",
        "Minimum",
        "Maximum",
        "Standard Deviation",
        "Coefficient of Variation (CV%)",
    ],
    "PP - Autoconer Q2": [
        "Count Name",
        "Consignee Name",
        "N",
        "S",
        "L",
        "LH1",
        "LH2",
        "LH3",
        "LH4",
        "LH5",
        "LH6",
        "THT",
        "TH1",
        "TH2",
        "TH3",
        "TH4",
        "TH5",
        "TH6",
        "CP",
        "CM",
        "CCP",
        "CCM",
        "PC",
        "Fault Distance",
        "No. of Faults",
        "JP",
        "JM",
        "UP",
        "FL",
        "FLH1",
        "FLH2",
        "FLH3",
        "FLH4",
        "FD",
        "FDH1",
        "FDH2",
        "FDH3",
        "FDH4",
        "FDH5",
        "Reference Length",
        "Measurement",
        "Upper Alarm Limit",
        "Lower Alarm Limit",
        "Action",
    ],
    "PP - Autoconer Q3": [
        "Count Name",
        "Consignee Name",
        "NSL1",
        "NSL2",
        "NSL3",
        "NSL4",
        "NSL5",
        "NSL6",
        "NSL7",
        "T1",
        "T2",
        "T3",
        "T4",
        "T5",
        "PF Sensing",
        "PF No. of Periods",
        "OC",
        "CP",
        "CM",
        "CCP1",
        "CCP2",
        "CCM1",
        "CCM2",
        "JP1",
        "JP2",
        "JP3",
        "JP4",
        "JP5",
        "JP6",
        "JP7",
        "JP Clearing",
        "JP U%",
        "JP JM",
        "FD1",
        "FD2",
        "FD3",
        "FD4",
        "FD5",
        "FD6",
        "Reference Length",
        "Suction",
        "Measurement",
        "Upper Limit",
        "Lower Limit",
        "Action",
        "Suction Status",
        "Blocking",
    ],
    "Rewinding Study": [
        "Count Name (From)",
        "Actual Count",
        "Auto Coner No.",
        "Cone Tip",
        "Drum No.",
        "No. of Cones",
        "Fault Name",
        "No. of Faults",
        "% Fault",
        "Weight",
        "Length (meters)",
        "No. of Cuts",
        "Break / 1 Million Meter",
    ],
    "Cone Density": [
        "Entry ID",
        "Count Name (From)",
        "Auto Coner No.",
        "Drum From/To",
        "Cone Tip",
        "Base Dia (E) (D1)",
        "Nose Dia (E) (D2)",
        "Base Dia (I) (D3)",
        "Nose Dia (I) (D4)",
        "Slant Height (B1)",
        "Vertical Height (B2)",
        "Cone Weight (Gms)",
        "Volume (Cm3)",
        "Density (Gms / Cm3)",
        "Gms / Litre",
        "W.Speed (m/Min)",
        "cN Tension",
        "Tensioner RPM",
        "Tensioner Force",
        "N Cradle Pressure",
        "Remarks (optional)",
        "Volume - Average Value",
        "Volume - Minimum Value",
        "Volume - Maximum Value",
        "Volume - Range",
        "Density - Average Value",
        "Density - Minimum Value",
        "Density - Maximum Value",
        "Density - Range",
        "Gms / Litre - Average Value",
        "Gms / Litre - Minimum Value",
        "Gms / Litre - Maximum Value",
        "Gms / Litre - Range",
    ],
    "Cone Packing Audit": [
        "Type",
        "Count Name",
        "Gross Wt. (Std)",
        "Gross Wt. (Act)",
        "Box Colour",
        "Cone Colour",
        "Gum Tape Colour",
        "Count Label",
        "Cone Damage",
        "Cover Missing",
        "Cone Hardness",
        "Stap Cone",
        "Disk",
        "Barcode",
        "Center Pad",
        "Net Weight",
        "Tare Weight",
        "Strap Colour",
    ],
    "Lycra % Checking": [
        "Lycra Draft",
        "Count Name",
        "No. of Readings",
        "Lycra Weight",
        "Fibre Weight",
        "Total Weight",
        "Lycra %",
        "Avg Length",
    ],
    "Count Wise Cuts Record": [
        "Machine No.",
        "Count",
        "Cone Tip",
        "Lot No.",
        "Frame No.",
        "YF",
        "YJ",
        "N",
        "S",
        "L",
        "T",
        "CP",
        "CM",
        "CCP",
        "CCM",
        "PC",
        "FD",
        "JP",
        "JM",
        "CVT",
        "A1",
        "A2",
        "A3",
        "A4",
        "B1",
        "B2",
        "B3",
        "B4",
        "C1",
        "C2",
        "C3",
        "C4",
        "D1",
        "D2",
        "D3",
        "D4",
        "E",
        "F",
        "G",
        "H1",
        "H2",
        "I1",
        "I2",
    ],
    "Splice Strength": [
        "Test No",
        "Count Name",
        "Auto Coner No.",
        "Drum From",
        "Drum To",
        "Cone Tip",
        "CSP Value",
        "Average",
        "No. of Readings",
        "Drum No",
        "Reading Number",
        "Splice Strength",
        "Parent Yarn Strength",
        "Percent Yarn",
    ],
    "Drum wise Appearance": [
        "Test No",
        "Count Name",
        "Auto Coner No.",
        "Drum From",
        "Drum To",
        "Appearance OK Count",
        "Appearance Not OK Count",
        "Remarks",
    ],
    "CSP Parameter Entries": [
        "Act Count",
        "Strength",
        "Count CV",
        "Strength CV",
        "CSP",
        "Cone Color",
        "U%",
        "CVM",
        "1Mtr CV",
        "3Mtr CV",
        "10Mtr CV",
        "BR 1.5mm",
        "CVB",
        "Thin -50%",
        "Thick +50%",
        "Neps +200%",
        "Thin -40%",
        "Thick +35%",
        "Thick +70%",
        "Neps +140%",
        "Thin -30%",
        "Neps +400%",
        "Total",
    ],
    "U% Parameter Entries": [
        "Act Count",
        "Strength",
        "CV1",
        "CV2",
        "CSP",
        "Cone Color",
        "U%",
        "CVM",
        "1Mtr CV",
        "3Mtr CV",
        "10Mtr CV",
        "BR 1.5mm",
        "CVB",
        "Thin -50%",
        "Thick +50%",
        "Neps +200%",
        "Thin -40%",
        "Thick +35%",
        "Thick +70%",
        "Neps +140%",
        "Thin -30%",
        "Neps +400%",
        "TOTAL",
    ],
    Carding: [
        "S.No",
        "Date",
        "ID",
        "Test ID",
        "Report Date",
        "Mac Name",
        "Shift",
        "Std. Hank",
        "Avg. Hank",
        "SD",
        "CV",
        "User",
        "Remark",
    ],
    Drawing: [
        "S.No",
        "Date",
        "ID",
        "Test ID",
        "Report Date",
        "Mac Name",
        "Shift",
        "Std. Hank",
        "Avg. Hank",
        "SD",
        "CV",
        "User",
        "Remark",
    ],
    Simplex: [
        "S.No",
        "Date",
        "ID",
        "Test ID",
        "Report Date",
        "Mac Name",
        "Shift",
        "Std. Hank",
        "Avg. Hank",
        "SD",
        "CV",
        "User",
        "Remark",
    ],
    "Blow Room Sync": [
        "Line No.",
        "Variety",
        "Checked By",
        "Beater",
        "Number of Rows (N)",
        "Run Time (Seconds)",
        "Idle Time (Seconds)",
        "Sub Total Time",
        "Sync Percentage (%)",
        "Grand Total Time (HH:MM:SS)",
    ],
    "Individual Card Waste Study": [
        "Entry ID",
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Cylinder Speed",
        "Lickerin Speed",
        "Flat Speed",
        "Doffer Speed",
        "Delivery Speed",
        "Wing Setting",
        "Wing Settling 1",
        "Wing Settling 2",
        "1st Lickerin Speed",
        "2nd Lickerin Speed",
        "3rd Lickerin Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste KGs Value",
        "Waste KGs %",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Overall Waste %",
        "Remarks",
    ],
    "BR Waste Study Entry": [
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Cylinder Speed",
        "Lickerin Speed",
        "Flat Speed",
        "Doffer Speed",
        "Delivery Speed",
        "Wing Setting",
        "Wing Settling 1",
        "Wing Settling 2",
        "1st Lickerin Speed",
        "2nd Lickerin Speed",
        "3rd Lickerin Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste KGs Value",
        "Waste KGs %",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Overall Waste %",
        "Remarks",
    ],
    "Drop Test Data Entry": [
        "Variety",
        "Blend",
        "Number of Tufts (N)",
        "Tuft Variety",
        "Display Wt.",
        "Actual Wt.",
        "Average Wt.",
        "Diff (Actual Wt. - Display Wt.)",
        "Ratio (Average Wt. / Total) * 100",
    ],
    "B/R CV1M Data Entry Within Lap": [
        "Machine Name",
        "Variety",
        "Lap Weight (KGs)",
        "Lap Length (Mts)",
        "Grams / Meter",
        "Sample 1",
        "Sample 2",
        "Sample 3",
        "Sample 4",
        "Sample 5",
        "Average",
        "Minimum",
        "Maximum",
        "Standard Deviation",
        "Coefficient of Variation (CV%)",
    ],
    "B/R Between Lap CV%": [
        "Machine Name",
        "Variety",
        "Lap Weight (KGs)",
        "Lap Length (Mts)",
        "Grams / Meter",
        "Sample 1",
        "Sample 2",
        "Sample 3",
        "Sample 4",
        "Sample 5",
        "Average",
        "Minimum",
        "Maximum",
        "Standard Deviation",
        "Coefficient of Variation (CV%)",
    ],
    "Simplex::Wheel Change": [
        "SMX No.",
        "SMX No. (Proposed)",
        "Mixing / Process - Existing",
        "Mixing / Process - Proposed",
        "Blend - Existing",
        "Blend - Proposed",
        "Feed - Hank - Existing",
        "Feed - Hank - Proposed",
        "Delivery - Hank - Existing",
        "Delivery - Hank - Proposed",
        "CP - Existing",
        "CP - Proposed",
        "SMXID - Existing",
        "SMXID - Proposed",
        "Break Draft (CP) - Existing",
        "Break Draft (CP) - Proposed",
        "Total Draft - Existing",
        "Total Draft - Proposed",
        "Front Roller Dia - Existing",
        "Front Roller Dia - Proposed",
        "TW - Existing",
        "TW - Proposed",
        "TCW [G] - Existing",
        "TCW [G] - Proposed",
        "TCW [H] - Existing",
        "TCW [H] - Proposed",
        "TPI - Existing",
        "TPI - Proposed",
        "TM - Existing",
        "TM - Proposed",
        "LW - Existing",
        "LW - Proposed",
        "LCW [E] - Existing",
        "LCW [E] - Proposed",
        "LCW [F] - Existing",
        "LCW [F] - Proposed",
        "Break Draft - Existing",
        "Break Draft - Proposed",
        "Bottom Roller Setting - Existing",
        "Bottom Roller Setting - Proposed",
        "Top Arm Setting - Existing",
        "Top Arm Setting - Proposed",
        "Top Arm Load - Existing",
        "Top Arm Load - Proposed",
        "Floating Condenser - Existing",
        "Floating Condenser - Proposed",
        "Spacer - Existing",
        "Spacer - Proposed",
        "Tension - Existing",
        "Tension - Proposed",
        "Creel Draft Change (WE) - Existing",
        "Creel Draft Change (WE) - Proposed",
        "Creel Draft - Existing",
        "Creel Draft - Proposed",
        "Bobbin Colour - Existing",
        "Bobbin Colour - Proposed",
        "Remarks",
    ],
    // Stretch % PDFs can OCR into any number of tables, each with any number of sample rows —
    // capped here at 4 tables x 6 samples (a practical upper bound) since Custom Report's field
    // list has to be generated ahead of time. Entries beyond this cap won't get columns.
    "Stretch %": Array.from({ length: 4 }, (_, i) => i + 1).flatMap((tableNo) => [
        `Table ${tableNo} - Test ID`,
        `Table ${tableNo} - Total Test`,
        `Table ${tableNo} - Number of Entries (N)`,
        `Table ${tableNo} - Length`,
        `Table ${tableNo} - Tester`,
        `Table ${tableNo} - Std. Stretch %`,
        `Table ${tableNo} - Stretch %`,
        `Table ${tableNo} - Remark`,
        ...Array.from({ length: 6 }, (_, i) => i + 1).flatMap((sampleNo) => [
            `Table ${tableNo} - Sample ${sampleNo} - Initial Bobbin`,
            `Table ${tableNo} - Sample ${sampleNo} - Full Bobbin`,
        ]),
        ...["Hank", "SD", "CV"].flatMap((label) => [
            `Table ${tableNo} - Summary ${label} - Initial Bobbin`,
            `Table ${tableNo} - Summary ${label} - Full Bobbin`,
        ]),
    ]),
    "SMXCots Change Data Entry": [
        "Entry ID",
        "Date",
        "MC Name",
        "Front Cots Damage",
        "Third Cots Damage",
        "Back Cots Damage",
        "Apron Damage",
        "Front Cots Tilting",
        "Second Cots Tilting",
        "Third Cots Tilting",
        "Back Cots Tilting",
        "Cradle Lifting",
        "Floating Condensor Missing",
        "Middle Condensor Missing",
        "Back Condensor Missing",
        "Others 1",
        "Others 2",
    ],
    "SMX Breaks Study Report": [
        "Simplex No.",
        "Date",
        "Start Time",
        "End Time",
        "Total Minutes",
        "TPI",
        "TPM",
        "Start HK",
        "Finish HK",
        "Average Speed",
        "Hank",
        "Mixing",
        "Roving HK",
        "Doff Length",
        "RH%",
        "TEMP%",
        "Total Spindles",
        "Running Spindles",
        "Idle Spindles",
        "Sider Name",
        "Break Category",
        ...[
            "0-200", "201-400", "401-600", "601-800", "801-1000", "1001-1200", "1201-1400",
            "1401-1600", "1601-1800", "1801-2000", "2001-2200", "2201-2400", "2401-2600",
        ].flatMap((lengthRange) => [
            "Roving Breaks at Finger",
            "Roving Breaks at Front Roller Nip",
            "Roving Breaks at Between Flyer",
            "Undraft",
            "Top Roller Lapping",
            "Bottom Roller Lapping",
            "SLIVER BREAKS",
            "Can Exhaust",
            "Unknown Stop",
        ].map((columnLabel) => `Length ${lengthRange} - ${columnLabel}`)),
        "Total Breaks - Roving Breaks at Finger",
        "Total Breaks - Roving Breaks at Front Roller Nip",
        "Total Breaks - Roving Breaks at Between Flyer",
        "Total Breaks - Undraft",
        "Total Breaks - Top Roller Lapping",
        "Total Breaks - Bottom Roller Lapping",
        "Total Breaks - SLIVER BREAKS",
        "Total Breaks - Can Exhaust",
        "Total Breaks - Unknown Stop",
        "Grand Total",
        "No. of Breaks per 100 Spindles / Hr - Roving Breaks at Finger",
        "No. of Breaks per 100 Spindles / Hr - Roving Breaks at Front Roller Nip",
        "No. of Breaks per 100 Spindles / Hr - Roving Breaks at Between Flyer",
        "No. of Breaks per 100 Spindles / Hr - Undraft",
        "No. of Breaks per 100 Spindles / Hr - Top Roller Lapping",
        "No. of Breaks per 100 Spindles / Hr - Bottom Roller Lapping",
        "No. of Breaks per 100 Spindles / Hr - SLIVER BREAKS",
        "Total No. of Breaks/100SH",
    ],
    "1 Yard / Half Yard CV Entry": [
        "Date",
        "Machine Number",
        "Remarks",
        "Number of Readings (N)",
        "AVG (1Y)",
        "HANK (1Y)",
        "SD (1Y)",
        "CV% (1Y)",
        "AVG (1/2Y)",
        "HANK (1/2Y)",
        "SD (1/2Y)",
        "CV% (1/2Y)",
    ],
    "Draw Frame Cots Data Entry": [
        "Date",
        "Shift",
        "Process Type",
        "Machine",
        "Fan Waste",
        "Cot Change",
        "Stripper Waste",
        "Auto Leveller",
        "Sliver Monitor",
        "Mass Thick Place",
        "Scanning Roller Area",
    ],
    "PP - Breaker Drawing": [
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
        "Creation Date",
        "Make",
        "No. of Ends",
        "Bottom Roll Setting",
        "Break Draft",
        "Total Draft",
        "Hank",
        "Web Tension Draft",
        "Trumpet Size",
        "Delivery Speed",
        "Pressure Bar",
    ],
    "PP - Finisher Drawing": [
        "Process Parameter ID",
        "Count Name",
        "Consignee Name",
        "Creation Date",
        "Make",
        "No. of Ends",
        "Bottom Roll Setting",
        "Break Draft",
        "Total Draft",
        "Web Tension Draft",
        "Trumpet Size",
        "Insert Size",
        "Web Funnel Size",
        "Delivery hank",
        "Delivery Speed",
        "Pressure Bar",
        "Scanning Roll Size",
    ],
    "A%": [
        "Report",
        "Test ID",
        "Machine",
        "Count System",
        "Length Unit",
        "Length",
        "Total Test",
        "Standard A%",
        "A% (N-1)",
        "A% (N+1)",
        "Date",
        "Tester",
        "Shift",
        "Process",
        "Remark",
        ...Array.from({ length: 10 }, (_, i) => i + 1).flatMap((sampleNo) => [
            `Sample ${sampleNo} - N-1`,
            `Sample ${sampleNo} - N`,
            `Sample ${sampleNo} - N+1`,
        ]),
        ...["Average Weight", "Weight (Max)", "Weight (Min)", "Range", "Hank", "SD", "CV"].flatMap((label) => [
            `${label} - N-1`,
            `${label} - N`,
            `${label} - N+1`,
        ]),
    ],
};

export const getThresholdFieldsForScreen = (screenName, context) => {
    if (context && thresholdFieldCatalog[`${context}::${screenName}`]) {
        return thresholdFieldCatalog[`${context}::${screenName}`];
    }
    return thresholdFieldCatalog[screenName] || [];
};
