export const thresholdFieldCatalog = {
    "Mixing::Process Parameter": [
        "Created Date",
        "Count Name",
        "Consignee Name",
        "Lot No.",
        "Blend No.",
        "Blend-1",
        "Cut Length",
        "Tenacity",
        "Elongation",
        "Merge No.",
    ],
    "Mixing::Cotton HVI Data Entry": [
        "Lot No.",
        "Variety",
        "Invoice No",
        "Invoice Date",
        "SCI",
        "Span Length (2.5%)",
        "Mic",
        "GTEX",
        "Maturity",
        "UR",
        "SFI",
        "Elongation",
        "Yellow + B",
        "TrCnt",
        "TrAr",
        "TrID",
        "Invisible Loss %",
        "Trash Content %",
        "RD",
        "Colour Grade",
    ],
    "Mixing::Fibre Data Entry": [
        "Lot No.",
        "Variety",
        "Invoice No",
        "Invoice Date",
        "Cut Length",
        "Length CV",
        "Mean Denier",
        "CV per Denier",
        "Tenacity",
        "CV per Tenacity",
        "Elongation",
        "CV per Elongation",
        "Crimp (ARC/CM)",
        "Whiteness Index",
        "Spin Finish",
    ],
    "Mixing::AFIS Data Entry": [
        "Lot No.",
        "Variety",
        "Invoice No",
        "Invoice Date",
        "UQL",
        "L5%",
        "SFC(N)",
        "IFC %",
        "Fibre Neps Gms",
        "SFC(W)",
        "Maturity",
        "Fineness",
        "SCN/gm",
    ],
    "Mixing::AFIS-6 Cotton Data Entry": [
        "Lot No.",
        "Variety",
        "Invoice Date",
        "Created Date",
        "Mc. Name",
        "Blow Room",
        "Carding",
        "Breaker Drawing",
        "Finisher Drawing",
        "Comber",
        "SCP NEP Count",
        "L(W)",
        "L(W) CV",
        "SCF(W)<12.70mm",
        "UQL(w)",
        "L(n)",
        "L(n)CV",
        "SCF(n)<12.70mm",
        "5%L(n)",
    ],
    "Mixing::AFIS-6 MMF Data Entry": [
        "Lot No.",
        "Variety",
        "Invoice Date",
        "Created Date",
        "Mc. Name",
        "Blow Room",
        "Carding",
        "Breaker Drawing",
        "Finisher Drawing",
        "Comber",
        "Total Nep Count / g",
        "Total Nep mean size",
        "Fiber Nep Count",
        "Fiber Nep Mean Size",
        "SC Nep Count",
        "SC Nep Mean Size",
        "L(w)",
        "L(w)CV",
        "SCF(w)<12.70mm",
        "UQL(w)",
        "L(n)",
        "L(n)CV",
        "SCF(n)<12.70mm",
        "5%L(n)",
        "Fitness Index",
        "Maturity Ratio Mat 1",
        "IFC%",
        "50%L(n)",
        "Cut Length(n)",
        "Fineness Den",
        "Fineness CV",
        "Long Fiber >45.60mm",
        "Long Fiber Count >45.60mm",
    ],
    "Blow Room::Blow Room Sync": [
        "Line No",
        "Variety",
        "Checked By",
        "Beater",
        "Number of Rows (N)",
        "Run Time (Seconds)",
        "Idle Time (Seconds)",
        "Sub Total Time",
        "Sync Percentage (%)",
        "Grand Total Time (HH:MM:SS)",
    ],
    "Blow Room::BR Waste Study T-1": [
        "Variety",
        "Carding Production (KGs)",
        "Cylinder Speed",
        "Lickerin Speed",
        "Flat Speed",
        "Doffer Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste Kgs Value",
        "Waste Kgs Percent",
        "Overall Waste",
        "Remarks",
    ],
    "Blow Room::BR Waste Study T-2": [
        "Variety",
        "Carding Production (KGs)",
        "Cylinder Speed",
        "Flat Speed",
        "Delivery Speed",
        "Wing Setting",
        "Lickerin Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste Kgs Value",
        "Waste Kgs Percent",
        "Overall Waste",
        "Remarks",
    ],
    "Blow Room::BR Waste Study T-3": [
        "Variety",
        "Carding Production (KGs)",
        "Flat Speed",
        "Delivery Speed",
        "Wing Settling 1",
        "Wing Settling 2",
        "1st Lickerin Speed",
        "2nd Lickerin Speed",
        "3rd Lickerin Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste Kgs Value",
        "Waste Kgs Percent",
        "Overall Waste",
        "Remarks",
    ],
    "Blow Room::Drop Test Data Entry": [
        "Variety",
        "Blend",
        "No. of Tufts",
        "Tuft Variety",
        "Display Wt.",
        "Actual Wt.",
        "Average Wt.",
        "Diff (Actual Wt. - Display Wt.)",
        "Ratio (Average Wt. / Total) * 100",
    ],
    "Blow Room::B/R CV1M Data Entry Within Lap": [
        "Machine",
        "Variety",
        "Lap Weight (KGs)",
        "Lap Length (Mts)",
        "Grams / Meter",
        "Sample 1",
        "Average",
        "Minimum",
        "Maximum",
        "Standard Deviation",
        "Coefficient of Variation (CV%)",
    ],
    "Blow Room::B/R Between Lap CV%": [
        "Machine",
        "Variety",
        "Lap Weight (KGs)",
        "Lap Length (Mts)",
        "Grams / Meter",
        "Sample 1",
        "Average",
        "Minimum",
        "Maximum",
        "Standard Deviation",
        "Coefficient of Variation (CV%)",
    ],
    "Blow Room::Process Parameter": [
        "Count Name",
        "Consignee Name",
        "Line Numbers",
        "Rotary Beater Speed",
        "Depth",
        "MPM Delivery Speed",
        "MPM Delivery Pascals",
        "Condensor Speed",
        "RK Feed Roll Beater",
        "RK Beater Speed",
        "Flexi to Feed Roll Beater",
        "Flexi Beater Speed",
        "Scutcher No",
        "RK MO Speed",
        "KB Speed",
        "Grid Bar",
        "Lap Weight",
        "Uniclean",
        "SRS",
        "RK Flexi",
    ],
    "Carding::Process Parameter": [
        "Entry ID",
        "Count Name",
        "Consignee Name",
        "Machine No.",
        "Lickerin Speed",
        "Cylinder Speed",
        "Flats Speed",
        "Delivery Speed",
        "Draft",
        "Tension Draft",
        "Delivery Hank",
        "Feed Roll to Lickerin",
        "Lickerin to Cylinder",
        "Cylinder to Flats",
        "Cylinder to Doffer",
        "SFL",
        "SFD",
        "Lickerin",
        "Cylinder",
        "Doffer",
        "Flats",
    ],
    "Simplex::Process Parameter": [
        "Count Name",
        "Consignee Name",
        "Machine No.",
        "Make",
        "Delivery Hank",
        "TPI / TM",
        "Speed",
        "Bottom Roller Setting",
        "Top Roller Setting",
        "Break Draft",
        "Total Draft",
        "Creel Draft",
        "Falls twister Grooves",
        "Spacer",
        "Top Arm Pressure",
        "Back Condensor",
        "Middle Condensor",
        "Front Condensor",
        "Coils/Inch",
        "Lifter Combination Wheel",
        "Lifter Wheel",
        "Tension Wheel",
    ],
    "Spinning::Process Parameter": [
        "Count Name",
        "Consignee Name",
        "Machine No.",
        "Bottom Roll Setting",
        "Top Roll Setting",
        "Break Draft",
        "Total Draft",
        "TPI/TM",
        "Spacer",
        "Traveller",
        "Speed",
        "Make",
        "Denier",
        "Mergen Number",
        "Slub Partcy Code",
        "Slub / Mtr",
        "Pause Min",
        "Pause Max",
        "Slub Min",
        "Slub Max",
        "Thickness Min",
        "Thickness Max",
        "Ramp",
        "Offset",
        "Lycra Draft",
        "Lycra %",
    ],
    "Autoconer::Process Parameter": [
        "Count Name",
        "Consignee Name",
        "Machine No.",
        "Drum No.",
        "Speed",
        "P Cone Identification",
        "Cone Weight",
        "Initial Winding Tension",
        "Standard Winding Tension",
        "Touch Winding Tension",
        "Release Add Tension",
        "Tension Release End Yarn Layer",
        "Tension Release Decrease Ratio",
        "Tension Release Valid Yarn Layer",
        "Splicing Setting",
        "Water On / Off",
        "Splicing Length Adjust Parameter",
        "Splicing Nozzle",
        "Cradle Pressure",
        "Cone Density",
        "Cone / Cops",
    ],
    "Process Parameter": [
        "Count Name",
        "Consignee Name",
        "Creation Date",
        "Machine No.",
        "Bottom Roll Setting",
        "Top Roll Setting",
        "Break Draft",
        "Total Draft",
        "TPI/TM",
        "Spacer",
        "Traveller",
        "Speed",
        "Make",
        "Denier",
        "Mergen Number",
        "Lycra Draft",
        "Lycra %",
    ],
    "Cotton HVI Data Entry": [
        "Variety",
        "Invoice No",
        "Invoice Date",
        "Created Date",
        "SCI",
        "Span Length (2.5%)",
        "Mic",
        "GTEX",
        "Maturity",
        "UR",
        "SFI",
        "Elongation",
        "Yellow + B",
        "TrCnt",
        "TrAr",
        "TrID",
        "Invisible Loss %",
        "Trash Content %",
        "RD",
        "Colour Grade",
    ],
    "Fibre Data Entry": [
        "Variety",
        "Invoice No",
        "Invoice Date",
        "Created Date",
        "Cut Length",
        "Length CV",
        "Mean Denier",
        "CV per Denier",
        "Tenacity",
        "CV per Tenacity",
        "Elongation",
        "CV per Elongation",
        "Crimp(ARC/CM)",
        "Whiteness Index",
        "Spin Finish",
    ],
    "AFIS Data Entry": [
        "Variety",
        "Invoice No",
        "Invoice Date",
        "Created Date",
        "UQL",
        "L5%",
        "SFC(N)",
        "IFC %",
        "Fibre Neps Gms",
        "SFC(W)",
        "Maturity",
        "Fineness",
    ],
    "AFIS-6 Cotton": [
        "Entry ID",
        "Lot No.",
        "Variety",
        "Invoice Date",
        "Mc. Name",
        "Blow Room",
        "Carding",
        "Breaker Drawing",
        "Finisher Drawing",
        "Comber",
        "SCP NEP Count",
        "L(W)",
        "L(W) CV",
        "SCF(W)<12.70mm",
        "UQL(w)",
        "L(n)",
        "L(n)CV",
        "SCF(n)<12.70mm",
        "5%L(n)",
    ],
    "AFIS-6 MMF": [
        "Entry ID",
        "Machine",
        "Material Class",
        "Comment",
        "Total Nep Count / g",
        "Total Nep Mean Size µm",
        "Cut Length (n) mm",
        "L(n) CV %",
        "SFC(n) <12.70 mm %",
        "5% L(n) mm",
        "Fineness den",
        "Fineness CV %",
        "Long Fiber >46.80 mm %",
        "Long Fiber Count > 46.80 mm",
    ],
    "Moisture Data Entry": [
        "Created Date",
        "Party Lot No",
        "Variety",
        "Party Name",
        "PR No",
        "Value 1",
        "Value 2",
        "Value 3",
        "Value 4",
        "Value 5",
        "Value 6",
        "Value 7",
        "Value 8",
        "Value 9",
        "Value 10",
        "Average",
    ],
    "Openness Data Entry": [
        "Entry ID",
        "Created Date",
        "Actual Specific Volume (Target)",
        "No. of Entries (N)",
        "B/R Line No",
        "Avg. Weight (M)",
        "Avg. Volume (V)",
        "Average of Apparent Specific Vol (A=V/M)",
        "Average of Actual Op. Value (AOV)",
        "Openness %",
        "Overall Openness Efficiency (%)",
    ],
    "Between & Within Data Entry - Within": [
        "Test ID",
        "MC Name",
        "Inspection Type",
        "Number of Entries (N)",
        "Sample Weight Calculations - Avg",
        "Sample Weight Calculations - Max",
        "Sample Weight Calculations - Min",
        "Sample Weight Calculations - Range",
        "Sample Weight Calculations - SD",
        "Sample Weight Calculations - CV",
        "Hank Calculations - Avg",
        "Hank Calculations - Max",
        "Hank Calculations - Min",
        "Hank Calculations - Range",
        "Hank Calculations - SD",
        "Hank Calculations - CV",
    ],
<<<<<<< HEAD
    "Between & Within Data Entry - Between": [
        "Test ID",
        "MC Name",
        "Inspection Type",
        "Number of Entries (N)",
        "Sample Weight Calculations - Avg",
        "Sample Weight Calculations - Max",
        "Sample Weight Calculations - Min",
        "Sample Weight Calculations - Range",
        "Sample Weight Calculations - SD",
        "Sample Weight Calculations - CV",
        "Hank Calculations - Avg",
        "Hank Calculations - Max",
        "Hank Calculations - Min",
        "Hank Calculations - Range",
        "Hank Calculations - SD",
        "Hank Calculations - CV",
=======
    "Thick place & CV": [
        "Entry ID",
        "Machine",
        "Card Thick Place Value",
        "5m CV",
>>>>>>> b1d24e10695c71395ee88867c7bef650d3242cfa
    ],
    // Kept non-empty (even though "Entry ID" is auto-appended anyway and gets deduped) so this
    // screen's available fields don't fall back to inferring raw, ugly-titleCased column names
    // directly from the row (e.g. "Card Thick Place Cdg01") alongside the properly-labeled
    // per-machine columns generated dynamically in ReportsPage.jsx's availableFields.
    "Thick place & CV": ["Entry ID"],
    "Carding NRE%": [
        "Entry ID",
        "Machine Model",
        "Mc Name",
        "Cylinder Wire Specification - Specs",
        "Cylinder Wire Specification - Tonnage in Kgs (1)",
        "Cylinder Wire Specification - Tonnage in Kgs (2)",
        "Doffer Wire Specification - Specs",
        "Doffer Wire Specification - Tonnage in Kgs (1)",
        "Doffer Wire Specification - Tonnage in Kgs (2)",
        "Flat Wire Specification - Specs",
        "Flat Wire Specification - Tonnage in Kgs (1)",
        "Flat Wire Specification - Tonnage in Kgs (2)",
        "Lickerin Wire Specification - Specs",
        "Lickerin Wire Specification - Tonnage in Kgs (1)",
        "Lickerin Wire Specification - Tonnage in Kgs (2)",
        "Silver Hank",
        "Delivery Mtr / Min",
        "Fibre Nep / Gms card mat",
        "Fibre Nep / Gms in Silver",
        "Carding NRE%",
    ],
    "Carding::Wheel Change": [
        "Entry ID",
        "Approval Status",
        "Operator",
        "Entry Date",
        "CDO No",
        "CDG No Proposed",
        "Remarks",
        "Mixing - Existing",
        "Mixing - Proposed",
        "Blend % - Existing",
        "Blend % - Proposed",
        "Delivery Hank - Existing",
        "Delivery Hank - Proposed",
        "Feed Weight - Existing",
        "Feed Weight - Proposed",
        "Lickerin Speed 1 - Existing",
        "Lickerin Speed 1 - Proposed",
        "Lickerin Speed 2 - Existing",
        "Lickerin Speed 2 - Proposed",
        "Cylinder Speed - Existing",
        "Cylinder Speed - Proposed",
        "Flats Speed (MM/Min) - Existing",
        "Flats Speed (MM/Min) - Proposed",
        "Feed Plate to Lickerin - Existing",
        "Feed Plate to Lickerin - Proposed",
        "SFL - Existing",
        "SFL - Proposed",
        "SFD - Existing",
        "SFD - Proposed",
        "Cylinder to Flats - Existing",
        "Cylinder to Flats - Proposed",
        "Cylinder to Doffer - Existing",
        "Cylinder to Doffer - Proposed",
        "Web Speed Draft (MW-V4) - Existing",
        "Web Speed Draft (MW-V4) - Proposed",
        "LC Wing Setting - Existing",
        "LC Wing Setting - Proposed",
        "RR/RK Beater Speed - Existing",
        "RR/RK Beater Speed - Proposed",
    ],
    "Individual Card performance Data": [
        "Type",
        "Carding Machine No.",
        "Entry ID",
        "Time",
        "Raw Material / Mixing",
        "Count Name",
        "Spinning Machine Name",
        "Autoconer Machine Name",
        "Product",
        "Nature of Trial",
        "Total Cuts",
        "Neps Cuts",
        "Short Cuts",
        "Long Cuts",
        "Thin Cuts",
        "CP",
        "CM",
        "CCP",
        "CCM",
        "JP",
        "A1",
        "A2",
        "A3",
        "A4",
        "B1",
        "B2",
        "B3",
        "B4",
        "C1",
        "C2",
        "C3",
        "C4",
        "D1",
        "D2",
        "D3",
        "D4",
        "E",
        "F",
        "G",
        "H1",
        "H2",
        "I1",
        "I2",
        "CVP",
        "User ID",
        "U%",
        "CVM",
        "CVM cv%",
        "CVM 10 mtr",
        "DR 1.5m",
        "Thin -50%",
        "Thick +50%",
        "Neps +200%",
        "Total (Regular)",
        "Thin -40%",
        "Thick +35%",
        "Neps +140%",
        "Total (HS)",
        "Thin -30%",
        "Count",
        "CSP",
        "Yarn Remarks (optional)",
    ],
    "Carding::Nati Data Entry": [
        "Entry ID",
        "Variety",
        "Number of Neps Entries",
    ],
    "Comber::Nati Data Entry": [
        "Entry ID",
        "Variety",
        "Number of Neps Entries",
    ],
    "Nati Data Entry": [
        "Entry ID",
        "Variety",
        "Number of Neps Entries",
        "MC No",
        "Ratio into size-1.0",
        "Ratio into size-0.7",
        "Ratio into size-0.5",
    ],
    "Carding::U% Data Entry": [
        "Entry ID",
        "Shift",
        "Variety",
        "MC No.",
        "U%",
        "CVM",
        "1mCV",
        "3mCV",
        "Remarks",
    ],
    "Comber::U% Data Entry": [
        "Entry ID",
        "Shift",
        "Variety",
        "Department",
        "MC No.",
        "U%",
        "CVM",
        "1mCV",
        "3 mCV",
        "Remarks",
    ],
    "Comber NRE%": [
        "Entry ID",
        "Silver Hank",
        "Delivery Mtr / Min",
        "Comber Neps / Min",
        "Feed in mm / Nep",
        "Fiber Nep in Comber Lap / Gms",
        "Fiber Nep / Gms in Silver",
        "Comber NRE%",
    ],
    "Comber Efficiency": [
        "Entry ID",
        "Mc Name",
        "50% span length in LAP",
        "50% span length in Sliver",
        "Combing Efficiency",
    ],
    "Comber Nolis %": [
        "Entry ID",
        "Test ID",
        "Machine ID",
        "Total Test",
        "Number of Entries (N)",
        "Tester",
        "Std. Noils %",
        "Noils %",
    ],
    "Stretch %": [
        "Table No",
        "Test ID",
        "Total Test",
        "Number of Entries (N)",
        "Length",
        "Tester",
        "Std. Stretch %",
        "Stretch %",
        "Remark",
        "Sample No",
        "Initial Bobbin",
        "Full Bobbin",
    ],
    "U% Data Entry": [
        "Shift",
        "Variety",
        "MC No.",
        "U%",
        "CVM",
        "1mCV",
        "3mCV",
        "Remarks",
    ],
    "Card DFK Data": ["Entry ID"],
    "COTS Checking": [
        "Inspection Date",
        "Machine No.",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Count Change": [
        "Entry ID",
        "RF No.",
        "Lycra Draft",
        "Count Name (From)",
        "Count Name (To)",
        "No. of Readings",
<<<<<<< HEAD
    ],
    "Ring Frame Log Book": [
        "Entry ID",
=======
        "Reading No.",
        "Reading Value",
        "Count",
        "CV%",
        "Strength",
        "Mean",
        "CSP",
    ],
    "Ring Frame Log Book": [
        "Entry Date",
>>>>>>> b1d24e10695c71395ee88867c7bef650d3242cfa
        "Shift",
        "Checker Name",
        "Out of Center AC",
        "Out of Center RF",
        "Out of Center",
        "Fault Cops AC",
        "Fault Cops RF",
        "Fault Cops",
        "Total Cops AC",
        "Total Cops RF",
        "Grand Total",
        "Guide Roll",
        "Lycra Missing",
        "Others",
        "Comments",
    ],
    "Speed Checking": [
        "Inspection Date",
        "Machine",
        "Display Speed",
        "Spindle Speed",
        "Difference",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Lycra Missing": [
        "Inspection Date",
        "Machine",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Bottom Apron Checking": [
        "Inspection Date",
        "Machine",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Lycra Out of Centering": [
        "Inspection Date",
        "Machine",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Online": [
        "Inspection Date",
        "Machine",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "RSM & Lycrasensor Checking Offline": [
        "Inspection Date",
        "Machine",
        "LHS (Spindle Number)",
        "RHS (Spindle Number)",
        "LHS Remarks",
        "RHS Remarks",
    ],
    "Draw Frame::Wheel Change - Breaker Type 1": [
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Draft Constant",
        "NW1",
        "NW2",
        "Total Draft",
        "BDCP (W4 / Break Draft)",
        "Creel Tension (W1VWW2) / Creel Tension Draft",
        "Feed Tension (W8/VEG) / Feed Tension Draft",
        "Web Tension (W3) / Web Tension Draft",
        "Trumpet",
        "Bottom Roller Setting Front Zone",
        "Bottom Roller Setting Back Zone",
    ],
    "Draw Frame::Wheel Change - Breaker Type 2": [
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Total Draft (Formula)",
        "Total Draft from G1/G2 Combinations",
        "G1/G2",
        "BDCP (C4) / Break Draft",
        "Web Tension (C3) / Web Tension Draft",
        "Trumpet",
        "Bottom Roller Setting Front Zone",
        "Bottom Roller Setting Back Zone",
    ],
    "Draw Frame::Wheel Change - Breaker Type 3": [
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Total Draft (Formula)",
        "Total Draft from G1/G2 Combinations",
        "G1/G2",
        "BDCP (C4) / Break Draft",
        "Web Tension (C3) / Web Tension Draft",
        "Trumpet",
        "Bottom Roller Setting Front Zone",
        "Bottom Roller Setting Back Zone",
    ],
    "Draw Frame::Wheel Change - Finisher Type 1": [
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Total Draft",
        "Total Draft Constant",
        "NW1",
        "NW2",
        "Break Draft",
        "Back Roller Pulley Dia (W4)",
        "Middle Roller Pulley (VV)",
        "Creel Tension (W1) / Creel Draft",
        "Web Tension Wheel (W3) / Web Tension Draft",
        "Bottom Roller Setting Front Zone / Gauge in MM",
        "Bottom Roller Setting Back Zone / Gauge in MM",
        "Scanning Roller in mm",
        "Scanning Roller Load (kg)",
        "Sliver Funnel",
        "Web Guide Tube Dia",
        "Insert Bore Dia",
        "Trumpet",
    ],
    "Draw Frame::Wheel Change - Finisher Type 2": [
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Total Draft",
        "Total Draft Constant",
        "NW1",
        "NW2",
        "Break Draft Wheel (W4) / Break Draft (VV)",
        "Creel Tension (W1) / Creel Draft",
        "Web Tension Wheel (W3) / Web Tension Draft",
        "Feed Tension Wheel (W8) / Feed Tension Draft",
        "Bottom Roller Setting Front Zone",
        "Bottom Roller Setting Back Zone",
        "Scanning Roller in mm",
        "Trumpet",
    ],
    "Draw Frame::Wheel Change - Finisher Type 3": [
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Total Draft",
        "Break Draft Wheel (W4) / Break Draft",
        "Creel Tension (W1) / Creel Draft",
        "Web Tension Wheel (W3) / Web Tension Draft",
        "Feed Tension Wheel (W8) / Feed Tension Draft",
        "Bottom Roller Setting Front Zone",
        "Bottom Roller Setting Back Zone",
        "Scanning Roller in mm",
        "Trumpet",
    ],
    "Draw Frame::Wheel Change - Finisher Type 4": [
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Hank",
        "No. of Ends",
        "Speed",
        "Total Draft",
        "Break Draft Wheel / Break Draft",
        "Creel Tension (W1) / Creel Draft",
        "Web Tension Wheel (W3) / Web Tension Draft",
        "Feed Tension Wheel (W8) / Feed Tension Draft",
        "Bottom Roller Setting Front Zone / Gauge in MM",
        "Bottom Roller Setting Back Zone / Gauge in MM",
        "Scanning Roller in mm",
        "Trumpet",
    ],
    "Wheel Change": [
        "Wheel Change Type",
        "Test No",
        "R/F No.",
        "Count From - Existing",
        "Count From - Proposed",
        "Lycra Type - Existing",
        "Lycra Type - Proposed",
        "Lycra Draft - Existing",
        "Lycra Draft - Proposed",
        "Slub Code - Existing",
        "Slub Code - Proposed",
        "Ramp - Existing",
        "Ramp - Proposed",
        "Offset On/Off - Existing",
        "Offset On/Off - Proposed",
        "Cop or Cone Condition - Existing",
        "Cop or Cone Condition - Proposed",
        "Product Qty (Kgs) - Existing",
        "Product Qty (Kgs) - Proposed",
        "Roving Hank - Existing",
        "Roving Hank - Proposed",
        "Raving Hank - Existing",
        "Raving Hank - Proposed",
        "Back Roll Wheel - Existing",
        "Back Roll Wheel - Proposed",
        "Change Pinion - Existing",
        "Change Pinion - Proposed",
        "BDW - Existing",
        "BDW - Proposed",
        "BD - Existing",
        "BD - Proposed",
        "DCA - Existing",
        "DCA - Proposed",
        "DCB - Existing",
        "DCB - Proposed",
        "DFC - Existing",
        "DFC - Proposed",
        "DFF - Existing",
        "DFF - Proposed",
        "DC - Existing",
        "DC - Proposed",
        "TCW - Existing",
        "TCW - Proposed",
        "TW - Existing",
        "TW - Proposed",
        "B - Existing",
        "B - Proposed",
        "A - Existing",
        "A - Proposed",
        "D - Existing",
        "D - Proposed",
        "C - Existing",
        "C - Proposed",
        "TPI/TM - Existing",
        "TPI/TM - Proposed",
        "TPM - Existing",
        "TPM - Proposed",
        "Winding length in meters - Existing",
        "Winding length in meters - Proposed",
        "Ratchet Wheel - Existing",
        "Ratchet Wheel - Proposed",
        "Travellers No. - Existing",
        "Travellers No. - Proposed",
        "Spacer - Existing",
        "Spacer - Proposed",
        "Cop Weight - Existing",
        "Cop Weight - Proposed",
        "Cop Weight (Grms) - Existing",
        "Cop Weight (Grms) - Proposed",
        "Speed Initial (RPM) - Existing",
        "Speed Initial (RPM) - Proposed",
        "Speed Max (RPM) - Existing",
        "Speed Max (RPM) - Proposed",
        "Empties Colour - Existing",
        "Empties Colour - Proposed",
        "Total Draft - Existing",
        "Total Draft - Proposed",
        "Range - Existing",
        "Range - Proposed",
        "Core Condition - Existing",
        "Core Condition - Proposed",
        "Production (Kgs) - Existing",
        "Production (Kgs) - Proposed",
        "EOW - Existing",
        "EOW - Proposed",
        "EPI - Existing",
        "EPI - Proposed",
        "Speed Front (RPM) - Existing",
        "Speed Front (RPM) - Proposed",
        "Speed (RPM) - Existing",
        "Speed (RPM) - Proposed",
    ],
    "Wheel Change Type 1": [
        "Entry ID",
        "Test No",
        "R/F No.",
        "Date",
        "Count From",
        "Lycra Type",
        "Lycra Draft",
        "Slub Code",
        "Ramp",
        "Offset On/Off",
        "Cop or Cone Condition",
        "Product Qty (Kgs)",
        "Roving Hank",
        "BDW",
        "BD",
        "DCA",
        "DCB",
        "DFC",
        "DC",
        "TCW",
        "TW",
        "TPI/TM",
        "Travellers No.",
        "Spacer",
        "Cop Weight (Grms)",
        "Speed Initial (RPM)",
        "Speed Max (RPM)",
        "Empties Colour",
        "Total Draft",
    ],
    "Wheel Change Type 2": [
        "Entry ID",
        "Test No",
        "R/F No.",
        "Date",
        "Count From",
        "Lycra Type",
        "Lycra Draft",
        "Slub Code",
        "Ramp",
        "Offset On/Off",
        "Cop or Cone Condition",
        "Product Qty (Kgs)",
        "Raving Hank",
        "Back Roll Wheel",
        "Change Pinion",
        "BDW",
        "BD",
        "B",
        "A",
        "D",
        "C",
        "TPI/TM",
        "Winding length in meters",
        "Ratchet Wheel",
        "Travellers No.",
        "Spacer",
        "Speed Initial (RPM)",
        "Speed Max (RPM)",
        "Empties Colour",
        "Total Draft",
    ],
    "Wheel Change Type 3": [
        "Entry ID",
        "Test No",
        "R/F No.",
        "Date",
        "Count From",
        "Lycra Type",
        "Lycra Draft",
        "Slub Code",
        "Ramp",
        "Offset On/Off",
        "Cop or Cone Condition",
        "Product Qty (Kgs)",
        "Raving Hank",
        "BDW",
        "BD",
        "DCA",
        "DCB",
        "DFF",
        "DC",
        "TCW",
        "TW",
        "TPI/TM",
        "Travellers No.",
        "Spacer",
        "Cop Weight",
        "Speed Initial (RPM)",
        "Speed Max (RPM)",
        "Empties Colour",
        "Total Draft",
    ],
    "Wheel Change Type 4": [
        "Entry ID",
        "Test No",
        "R/F No.",
        "Date",
        "Count From",
        "Lycra Type",
        "Lycra Draft",
        "Slub Code",
        "Range",
        "Offset On/Off",
        "Core Condition",
        "Production (Kgs)",
        "Roving Hank",
        "EOW",
        "EPI",
        "DCA",
        "DCB",
        "DFC",
        "DC",
        "TCW",
        "TW",
        "TPM",
        "Travellers No.",
        "Spacer",
        "Cop Weight",
        "Speed Front (RPM)",
        "Speed (RPM)",
        "Empties Colour",
        "Total Draft",
        "BDW",
        "BD",
        "Winding length in meters",
    ],
    WheelChange: [
        "Type",
        "Entry ID",
        "CDG No. (Proposed)",
        "Mixing",
        "Blend %",
        "Del-Hank",
        "Feed Weight",
        "Licker-in Speed 1",
        "Licker-in Speed 2",
        "Cylinder Speed",
        "Flats Speed in mm/min",
        "Feed Plate to Licker-in",
        "SFL",
        "SFD",
        "Cylinder to Flats",
        "Cylinder to Doffer",
        "Web Speed Draft MW(V4)",
        "LC-Wing Setting",
        "BR-RK Beater Speed",
        "Remarks (optional)",
    ],
    "Ribbon Lap CV1M Data Entry": [
        "Entry ID",
        "Machine Name",
        "Variety",
        "Lap Weight (KGs)",
        "Lap Length (Mts)",
        "Grams / Meter",
<<<<<<< HEAD
=======
        "Sample 1",
>>>>>>> b1d24e10695c71395ee88867c7bef650d3242cfa
        "Average",
        "Minimum",
        "Maximum",
        "Standard Deviation",
        "Coefficient of Variation (CV%)",
    ],
    "PP - Autoconer Q2": [
        "Count Name",
        "Consignee Name",
        "N",
        "S",
        "L",
        "LH1",
        "LH2",
        "LH3",
        "LH4",
        "LH5",
        "LH6",
        "THT",
        "TH1",
        "TH2",
        "TH3",
        "TH4",
        "TH5",
        "TH6",
        "CP",
        "CM",
        "CCP",
        "CCM",
        "PC",
        "Fault Distance",
        "No. of Faults",
        "JP",
        "JM",
        "UP",
        "FL",
        "FLH1",
        "FLH2",
        "FLH3",
        "FLH4",
        "FD",
        "FDH1",
        "FDH2",
        "FDH3",
        "FDH4",
        "FDH5",
        "Reference Length",
        "Measurement",
        "Upper Alarm Limit",
        "Lower Alarm Limit",
        "Action",
    ],
    "PP - Autoconer Q3": [
        "Count Name",
        "Consignee Name",
        "NSL1",
        "NSL2",
        "NSL3",
        "NSL4",
        "NSL5",
        "NSL6",
        "NSL7",
        "T1",
        "T2",
        "T3",
        "T4",
        "T5",
        "PF Sensing",
        "PF No. of Periods",
        "OC",
        "CP",
        "CM",
        "CCP1",
        "CCP2",
        "CCM1",
        "CCM2",
        "JP1",
        "JP2",
        "JP3",
        "JP4",
        "JP5",
        "JP6",
        "JP7",
        "JP Clearing",
        "JP U%",
        "JP JM",
        "FD1",
        "FD2",
        "FD3",
        "FD4",
        "FD5",
        "FD6",
        "Reference Length",
        "Suction",
        "Measurement",
        "Upper Limit",
        "Lower Limit",
        "Action",
        "Suction Status",
        "Blocking",
    ],
    "Rewinding Study": [
        "Entry ID",
        "Count Name (From)",
        "Actual Count",
        "Auto Coner No.",
        "Cone Tip",
        "No. of Cuts",
        "Break / 1 Million Meter",
        "Remarks",
    ],
    "Cone Density": [
        "Entry ID",
        "Count Name (From)",
        "Auto Coner No.",
        "Drum From",
        "Drum To",
        "Cone Tip",
        "Remarks",
        "Volume - Average Value",
        "Volume - Minimum Value",
        "Volume - Maximum Value",
        "Volume - Range",
        "Density - Average Value",
        "Density - Minimum Value",
        "Density - Maximum Value",
        "Density - Range",
        "Gms / Litre - Average Value",
        "Gms / Litre - Minimum Value",
        "Gms / Litre - Maximum Value",
        "Gms / Litre - Range",
    ],
    "Cone Packing Audit": [
        "Count Name",
        "Gross Wt. (Std)",
        "Gross Wt. (Act)",
        "Box Colour",
        "Cone Colour",
        "Gum Tape Colour",
        "Count Label",
        "Cone Damage",
        "Cover Missing",
        "Cone Hardness",
        "Stap Cone",
        "Disk",
        "Barcode",
        "Center Pad",
        "Net Weight",
        "Tare Weight",
        "Strap Colour",
    ],
    "Lycra % Checking": [
        "Entry ID",
        "Lycra Draft",
        "Count Name",
        "No. of Readings",
        "Lycra Weight",
        "Fibre Weight",
        "Total Weight",
        "Lycra %",
        "Avg Length",
    ],
    "Count Wise Cuts Record": [
        "Entry ID",
        "Machine No.",
        "Count",
        "Cone Tip",
        "Lot No.",
        "Frame No.",
        "YF",
        "YJ",
        "N",
        "S",
        "L",
        "T",
        "CP",
        "CM",
        "CCP",
        "CCM",
        "PC",
        "FD",
        "JP",
        "JM",
        "CVT",
        "A1",
        "A2",
        "A3",
        "A4",
        "B1",
        "B2",
        "B3",
        "B4",
        "C1",
        "C2",
        "C3",
        "C4",
        "D1",
        "D2",
        "D3",
        "D4",
        "E",
        "F",
        "G",
        "H1",
        "H2",
        "I1",
        "I2",
    ],
    "Splice Strength": [
        "Entry ID",
        "Test No",
        "Count Name",
        "Auto Coner No.",
        "Drum From",
        "Drum To",
        "Cone Tip",
        "CSP Value",
        "Average",
        "Avg Splice Strength",
        "Avg Parent Yarn",
        "Avg Percent Yarn",
        "Total Readings",
    ],
    "Drum wise Appearance": [
        "Entry ID",
        "Test No",
        "Count Name",
        "Auto Coner No.",
        "Drum From",
        "Drum To",
        "Appearance OK Count",
        "Appearance Not OK Count",
        "Remarks",
    ],
    "CSP Parameter Entries": [
        "Entry ID",
        "Act Count",
        "Strength",
        "Count CV",
        "Strength CV",
        "CSP",
        "Cone Color",
        "U%",
        "CVM",
        "1Mtr CV",
        "3Mtr CV",
        "10Mtr CV",
        "BR 1.5mm",
        "CVB",
        "Thin -50%",
        "Thick +50%",
        "Neps +200%",
        "Thin -40%",
        "Thick +35%",
        "Thick +70%",
        "Neps +140%",
        "Thin -30%",
        "Neps +400%",
        "Total",
    ],
    "U% Parameter Entries": [
        "Entry ID",
        "Act Count",
        "Strength",
        "CV1",
        "CV2",
        "CSP",
        "Cone Color",
        "U%",
        "CVM",
        "1Mtr CV",
        "3Mtr CV",
        "10Mtr CV",
        "BR 1.5mm",
        "CVB",
        "Thin -50%",
        "Thick +50%",
        "Neps +200%",
        "Thin -40%",
        "Thick +35%",
        "Thick +70%",
        "Neps +140%",
        "Thin -30%",
        "Neps +400%",
        "TOTAL",
    ],
    Carding: [
        "S.No",
        "Date",
        "ID",
        "Test ID",
        "Report Date",
        "Mac Name",
        "Shift",
        "Std. Hank",
        "Avg. Hank",
        "SD",
        "CV",
        "User",
        "Remark",
    ],
    Drawing: [
        "S.No",
        "Date",
        "ID",
        "Test ID",
        "Report Date",
        "Mac Name",
        "Shift",
        "Std. Hank",
        "Avg. Hank",
        "SD",
        "CV",
        "User",
        "Remark",
    ],
    Simplex: [
        "S.No",
        "Date",
        "ID",
        "Test ID",
        "Report Date",
        "Mac Name",
        "Shift",
        "Std. Hank",
        "Avg. Hank",
        "SD",
        "CV",
        "User",
        "Remark",
    ],
    "Blow Room Sync": [
        "Line No.",
        "Variety",
        "Checked By",
        "Beater",
        "Number of Rows (N)",
        "Run Time (Seconds)",
        "Idle Time (Seconds)",
        "Sub Total Time",
        "Sync Percentage (%)",
        "Grand Total Time (HH:MM:SS)",
    ],
    "Carding::Card Waste Study T-1": [
        "Variety",
        "Carding Production (KGs)",
        "Cylinder Speed",
        "Lickerin Speed",
        "Flat Speed",
        "Doffer Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste Kgs Value",
        "Waste Kgs Percent",
        "Overall Waste",
        "Remarks",
    ],
    "Carding::Card Waste Study T-2": [
        "Variety",
        "Carding Production (KGs)",
        "Cylinder Speed",
        "Flat Speed",
        "Delivery Speed",
        "Wing Setting",
        "Lickerin Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste Kgs Value",
        "Waste Kgs Percent",
        "Overall Waste",
        "Remarks",
    ],
    "Carding::Card Waste Study T-3": [
        "Variety",
        "Carding Production (KGs)",
        "Flat Speed",
        "Delivery Speed",
        "Wing Settling 1",
        "Wing Settling 2",
        "1st Lickerin Speed",
        "2nd Lickerin Speed",
        "3rd Lickerin Speed",
        "MC No",
        "MC Production",
        "Waste Type",
        "Waste Kgs Value",
        "Waste Kgs Percent",
        "Overall Waste",
        "Remarks",
    ],
    "BR Waste Study Entry Type 1": [
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Cylinder Speed",
        "Lickerin Speed",
        "Flat Speed",
        "Doffer Speed",
        "MC No",
        "MC Production",
        "No. of Waste Types",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Overall Waste %",
        "Remarks",
    ],
    "BR Waste Study Entry Type 2": [
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Cylinder Speed",
        "Flat Speed",
        "Delivery Speed",
        "Wing Setting",
        "Lickerin Speed",
        "MC No",
        "MC Production",
        "No. of Waste Types",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Overall Waste %",
        "Remarks",
    ],
    "BR Waste Study Entry Type 3": [
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Flat Speed",
        "Delivery Speed",
        "Wing Settling 1",
        "MC No",
        "MC Production",
        "No. of Waste Types",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Overall Waste %",
        "Remarks",
    ],
    "Individual Card Waste Study Type 1": [
        "Entry ID",
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Cylinder Speed",
        "Lickerin Speed",
        "Flat Speed",
        "Doffer Speed",
        "MC No",
        "MC Production",
        "No. of Waste Types",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Overall Waste %",
        "Remarks",
    ],
    "Individual Card Waste Study Type 2": [
        "Entry ID",
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Cylinder Speed",
        "Flat Speed",
        "Delivery Speed",
        "Wing Setting",
        "Lickerin Speed",
        "MC No",
        "MC Production",
        "No. of Waste Types",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Overall Waste %",
        "Remarks",
    ],
    "Individual Card Waste Study Type 3": [
        "Entry ID",
        "Variety",
        "Carding Production (KGs)",
        "Study Type",
        "Flat Speed",
        "Delivery Speed",
        "Wing Settling 1",
        "Wing Settling 2",
        "1st Lickerin Speed",
        "2nd Lickerin Speed",
        "3rd Lickerin Speed",
        "MC No",
        "MC Production",
        "No. of Waste Types",
        "Total Waste KGs Value",
        "Total Waste KGs %",
        "Overall Waste %",
        "Remarks",
    ],
    "Drop Test Data Entry": [
        "Variety",
        "Blend",
        "Number of Tufts (N)",
    ],
    "B/R CV1M Data Entry Within Lap": [
        "Machine Name",
        "Variety",
        "Lap Weight (KGs)",
        "Lap Length (Mts)",
        "Grams / Meter",
<<<<<<< HEAD
        "No. of Samples",
=======
        "Sample 1",
>>>>>>> b1d24e10695c71395ee88867c7bef650d3242cfa
        "Average",
        "Minimum",
        "Maximum",
        "Standard Deviation",
        "Coefficient of Variation (CV%)",
    ],
    "B/R Between Lap CV%": [
        "Machine Name",
        "Variety",
        "Lap Weight (KGs)",
        "Lap Length (Mts)",
        "Grams / Meter",
<<<<<<< HEAD
        "No. of Samples",
=======
        "Sample 1",
>>>>>>> b1d24e10695c71395ee88867c7bef650d3242cfa
        "Average",
        "Minimum",
        "Maximum",
        "Standard Deviation",
        "Coefficient of Variation (CV%)",
    ],
    "Simplex::Wheel Change": [
        "SMX No.",
        "SMX No. (Proposed)",
        "Mixing / Process",
        "Blend",
        "Feed - Hank",
        "Delivery - Hank",
        "CP",
        "SMXID",
        "Break Draft (CP)",
        "Total Draft",
        "Front Roller Dia",
        "TW",
        "TCW [G]",
        "TCW [H]",
        "TPI",
        "TM",
        "LW",
        "LCW [E]",
        "LCW [F]",
        "Break Draft",
        "Bottom Roller Setting",
        "Top Arm Setting",
        "Top Arm Load",
        "Floating Condenser",
        "Spacer",
        "Tension",
        "Creel Draft Change (WE)",
        "Creel Draft",
        "Bobbin Colour",
        "Remarks",
    ],
    // Stretch % PDFs can OCR into any number of tables, each with any number of sample rows —
    // capped here at 4 tables x 6 samples (a practical upper bound) since Custom Report's field
    // list has to be generated ahead of time. Entries beyond this cap won't get columns.
    "Stretch %": Array.from({ length: 4 }, (_, i) => i + 1).flatMap((tableNo) => [
        `Table ${tableNo} - Test ID`,
        `Table ${tableNo} - Total Test`,
        `Table ${tableNo} - Number of Entries (N)`,
        `Table ${tableNo} - Length`,
        `Table ${tableNo} - Tester`,
        `Table ${tableNo} - Std. Stretch %`,
        `Table ${tableNo} - Stretch %`,
        `Table ${tableNo} - Remark`,
        ...Array.from({ length: 6 }, (_, i) => i + 1).flatMap((sampleNo) => [
            `Table ${tableNo} - Sample ${sampleNo} - Initial Bobbin`,
            `Table ${tableNo} - Sample ${sampleNo} - Full Bobbin`,
        ]),
        ...["Hank", "SD", "CV"].flatMap((label) => [
            `Table ${tableNo} - Summary ${label} - Initial Bobbin`,
            `Table ${tableNo} - Summary ${label} - Full Bobbin`,
        ]),
    ]),
    "SMXCots Change Data Entry": [
        "Entry ID",
        "MC Name",
        "Front Cots Damage",
        "Third Cots Damage",
        "Back Cots Damage",
        "Apron Damage",
        "Front Cots Tilting",
        "Second Cots Tilting",
        "Third Cots Tilting",
        "Back Cots Tilting",
        "Cradle Lifting",
        "Floating Condensor Missing",
        "Middle Condensor Missing",
        "Back Condensor Missing",
        "Others 1",
        "Others 2",
    ],
    "SMX Breaks Study Report": [
        "Simplex No.",
        "Date",
        "Start Time",
        "End Time",
        "Total Minutes",
        "TPI",
        "TPM",
        "Start HK",
        "Finish HK",
        "Average Speed",
        "Hank",
        "Mixing",
        "Roving HK",
        "Doff Length",
        "RH%",
        "TEMP%",
        "Total Spindles",
        "Running Spindles",
        "Idle Spindles",
<<<<<<< HEAD
        "Break Category",
=======
        "Sider Name",
>>>>>>> b1d24e10695c71395ee88867c7bef650d3242cfa
        ...[
            "0-200", "201-400", "401-600", "601-800", "801-1000", "1001-1200", "1201-1400",
            "1401-1600", "1601-1800", "1801-2000", "2001-2200", "2201-2400", "2401-2600",
        ].flatMap((lengthRange) => [
            "Roving Breaks at Finger",
            "Roving Breaks at Front Roller Nip",
            "Roving Breaks at Between Flyer",
            "Undraft",
            "Top Roller Lapping",
            "Bottom Roller Lapping",
            "SLIVER BREAKS",
            "Can Exhaust",
            "Unknown Stop",
        ].map((columnLabel) => `Length ${lengthRange} - ${columnLabel}`)),
        "Total Breaks - Roving Breaks at Finger",
        "Total Breaks - Roving Breaks at Front Roller Nip",
        "Total Breaks - Roving Breaks at Between Flyer",
        "Total Breaks - Undraft",
        "Total Breaks - Top Roller Lapping",
        "Total Breaks - Bottom Roller Lapping",
        "Total Breaks - SLIVER BREAKS",
        "Total Breaks - Can Exhaust",
        "Total Breaks - Unknown Stop",
        "Grand Total",
        "No. of Breaks per 100 Spindles / Hr - Roving Breaks at Finger",
        "No. of Breaks per 100 Spindles / Hr - Roving Breaks at Front Roller Nip",
        "No. of Breaks per 100 Spindles / Hr - Roving Breaks at Between Flyer",
        "No. of Breaks per 100 Spindles / Hr - Undraft",
        "No. of Breaks per 100 Spindles / Hr - Top Roller Lapping",
        "No. of Breaks per 100 Spindles / Hr - Bottom Roller Lapping",
        "No. of Breaks per 100 Spindles / Hr - SLIVER BREAKS",
        "Total No. of Breaks/100SH",
    ],
    "1 Yard / Half Yard CV Entry": [
        "Machine Number",
        "Remarks",
        "Number of Readings (N)",
        "AVG (1Y)",
        "HANK (1Y)",
        "SD (1Y)",
        "CV% (1Y)",
        "AVG (1/2Y)",
        "HANK (1/2Y)",
        "SD (1/2Y)",
        "CV% (1/2Y)",
    ],
<<<<<<< HEAD
    "Draw Frame Cots Data Entry - Breaker": [
        "Entry ID",
        "Shift",
        "Process Type",
    ],
    "Draw Frame Cots Data Entry - Finisher": [
        "Entry ID",
=======
    "Draw Frame Cots Data Entry": [
>>>>>>> b1d24e10695c71395ee88867c7bef650d3242cfa
        "Shift",
        "Process Type",
    ],
    "PP - Breaker Drawing": [
        "Count Name",
        "Consignee Name",
        "Creation Date",
        "Make",
        "No. of Ends",
        "Bottom Roll Setting",
        "Break Draft",
        "Total Draft",
        "Hank",
        "Web Tension Draft",
        "Trumpet Size",
        "Delivery Speed",
        "Pressure Bar",
    ],
    "PP - Finisher Drawing": [
        "Count Name",
        "Consignee Name",
        "Creation Date",
        "Make",
        "No. of Ends",
        "Bottom Roll Setting",
        "Break Draft",
        "Total Draft",
        "Web Tension Draft",
        "Trumpet Size",
        "Insert Size",
        "Web Funnel Size",
        "Delivery hank",
        "Delivery Speed",
        "Pressure Bar",
        "Scanning Roll Size",
    ],
    "A%": [
        "Report",
        "Test ID",
        "Machine",
        "Count System",
        "Length Unit",
        "Length",
        "Total Test",
        "Standard A%",
        "A% (N-1)",
        "A% (N+1)",
        "Date",
        "Tester",
        "Shift",
        "Process",
        "Remark",
        ...Array.from({ length: 10 }, (_, i) => i + 1).flatMap((sampleNo) => [
            `Sample ${sampleNo} - N-1`,
            `Sample ${sampleNo} - N`,
            `Sample ${sampleNo} - N+1`,
        ]),
        ...["Average Weight", "Weight (Max)", "Weight (Min)", "Range", "Hank", "SD", "CV"].flatMap((label) => [
            `${label} - N-1`,
            `${label} - N`,
            `${label} - N+1`,
        ]),
    ],
};

export const getThresholdFieldsForScreen = (screenName, context) => {
    if (context && thresholdFieldCatalog[`${context}::${screenName}`]) {
        return thresholdFieldCatalog[`${context}::${screenName}`];
    }
    return thresholdFieldCatalog[screenName] || [];
};
