export const thresholdScreenCatalog = {
    "quality-control": {
        mixing: [
            "Process Parameter",
            "Cotton HVI Data Entry",
            "Fibre Data Entry",
            "AFIS Data Entry",
            "AFIS-6 Cotton",
            "AFIS-6 MMF",
            "Moisture Data Entry",
            "Openness Data Entry",
        ],
        "blow-room": [
            "Blow Room Sync",
            "Process Parameter",
            "BR Waste Study Entry",
            "Drop Test Data Entry",
            "B/R CV1M Data Entry Within Lap",
            "B/R Between Lap CV%",
        ],
        carding: [
            "Process Parameter",
            "Between & Within Data Entry - Within",
            "Between & Within Data Entry - Between",
            "Thick place & CV",
            "Carding NRE%",
            "Nati Data Entry",
            "U% Data Entry",
            "Card DFK Data",
            "WheelChange",
            "Individual Card Waste Study Type 1",
            "Individual Card Waste Study Type 2",
            "Individual Card Waste Study Type 3",
        ],
        comber: [
            "Ribbon Lap CV1M Data Entry",
            "Nati Data Entry",
            "U% Data Entry",
            "Comber NRE%",
            "Comber Efficiency",
            "Comber Nolis %",
        ],
        "individual-card-performance": [
            "Individual Card performance Data",
        ],
        "draw-frame": [
            "1 Yard / Half Yard CV Entry",
            "Draw Frame Cots Data Entry - Breaker",
            "Draw Frame Cots Data Entry - Finisher",
            "U% Data Entry",
            "A%",
            "PP - Breaker Drawing",
            "PP - Finisher Drawing",
            "Wheel Change - Breaker Type 1",
            "Wheel Change - Breaker Type 2",
            "Wheel Change - Breaker Type 3",
            "Wheel Change - Finisher Type 1",
            "Wheel Change - Finisher Type 2",
            "Wheel Change - Finisher Type 3",
            "Wheel Change - Finisher Type 4",
        ],
        simplex: [
            "Process Parameter",
            "SMXCots Change Data Entry",
            "SMX Breaks Study Report",
            "U% Data Entry",
            "Wheel Change",
            "Stretch %",
        ],
        spinning: [
            "Process Parameter",
            "COTS Checking",
            "Count Change",
            "Ring Frame Log Book",
            "Speed Checking",
            "Bottom Apron Checking",
            "Lycra Out of Centering",
            "RSM & Lycrasensor Checking Online",
            "RSM & Lycrasensor Checking Offline",
            "Wheel Change",
        ],
        autoconer: [
            "Process Parameter",
            "PP - Autoconer Q2",
            "PP - Autoconer Q3",
            "Rewinding Study",
            "Cone Density",
            "Cone Packing Audit",
            "Lycra % Checking",
            "Count Wise Cuts Record",
            "Splice Strength",
            "Drum wise Appearance",
            "CSP Parameter Entries",
            "U% Parameter Entries",
        ],
    },
    electrical: {
        maintenance: [],
        panels: [],
        utilities: [],
    },
    mechanical: {
        maintenance: [],
        machining: [],
        inspection: [],
    },
};

export const getThresholdScreensForSubDepartment = (departmentSlug, subDepartmentSlug) =>
    thresholdScreenCatalog?.[departmentSlug]?.[subDepartmentSlug] || [];
