export const thresholdScreenCatalog = {
    "quality-control": {
        mixing: [
            "Process Parameter",
            "Cotton HVI Data Entry",
            "AFIS Data Entry",
            "AFIS-6 Cotton Data Entry",
            "AFIS-6 MMF Data Entry",
            "Fibre Data Entry",
            "Moisture Data Entry",
            "Openness Data Entry",
        ],
        "blow-room": [
            "Blow Room Sync",
            "Process Parameter",
            "BR Waste Study T-1",
            "BR Waste Study T-2",
            "BR Waste Study T-3",
            "Drop Test Data Entry",
            "B/R CV1M Data Entry Within Lap",
            "B/R Between Lap CV%",
        ],
        carding: [
            "Process Parameter",
            "Between & Within Card Data Entry",
            "Thick place & CV",
            "Carding NRE%",
            "Nati Data Entry",
            "U% Data Entry",
            "Card DFK Data",
            "Card Waste Study T-1",
            "Card Waste Study T-2",
            "Card Waste Study T-3",
            "Wheel Change",
        ],
        comber: [
            "Ribbon Lap CV1M Data Entry",
            "Nati Data Entry",
            "U% Data Entry",
            "Comber Nolis %",
            "Comber NRE%",
            "Comber Efficiency",
        ],
        "individual-card-performance": [
            "Individual Card performance Data",
        ],
        "draw-frame": [
            "1 Yard / Half Yard CV Entry",
            "Draw Frame Cots Data Entry",
            "U% Data Entry",
            "PP - Breaker Drawing",
            "PP - Finisher Drawing",
            "Wheel Change Type-1 (SB20)",
            "Wheel Change Type-2 (TD7)",
            "Wheel Change Type-3 (TD9)",
            "Wheel Change Type-1 (LRSB)",
            "Wheel Change Type-2 (D40)",
            "Wheel Change Type-3 (D50/D55)",
            "Wheel Change Type-4 (LDF3S)",
        ],
        simplex: [
            "Process Parameter",
            "SMXCots Change Data Entry",
            "SMX Breaks Study Report",
            "U% Data Entry",
            "Wheel Change",
        ],
        spinning: [
            "Process Parameter",
            "COTS Checking",
            "Count Change",
            "Ring Frame Log Book",
            "Speed Checking",
            "Bottom Apron Checking",
            "Lycra Out of Centering",
            "RSM & Lycrasensor Checking Online",
            "RSM & Lycrasensor Checking Offline",
            "Wheel Change Type-1",
            "Wheel Change Type-2",
            "Wheel Change Type-3",
            "Wheel Change Type-4",
        ],
        autoconer: [
            "Process Parameter",
            "PP - Autoconer Q2",
            "PP - Autoconer Q3",
            "Rewinding Study",
            "Cone Density",
            "Cone Packing Audit",
            "Lycra % Checking",
            "Count Wise Cuts Record",
            "Splice Strength",
            "Drum wise Appearance",
            "CSP Parameter Entries",
            "U% Parameter Entries",
        ],
    },
    electrical: {
        maintenance: [],
        panels: [],
        utilities: [],
    },
    mechanical: {
        maintenance: [],
        machining: [],
        inspection: [],
    },
};

export const getThresholdScreensForSubDepartment = (departmentSlug, subDepartmentSlug) =>
    thresholdScreenCatalog?.[departmentSlug]?.[subDepartmentSlug] || [];
